### ISSUE TITLE
Add smooth transition on hover

### ISSUE THREAD

**Issue by supzi-del** [ALPHAVIO/WordNook#1000]
### Feature request-
In the testimonials section, when each box is hovered upon, the transition is kind of harsh

### Describe the solution you'd like
I would like to add a smooth transition to resolve this jerky motion.

`/assign`

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Pranav016** [comment]
You want to increase the time of the animation right ?

Also, you should comment the keyword below the issue to get it assigned, I'll assign it this time. You can keep it in mind for the next time 👍

**Comment by supzi-del** [comment]
Yes, precisely. I am working on this issue under LGM SOC'21...

**Comment by Pranav016** [comment]
> Yes, precisely. I am working on this issue under LGM SOC'21...can you please add the label?

Yes, the project admins have not received the official list of tags to be added for lgm soc, official list is imp. because tags can be case sensitive. I'll add the tags when I get it from the organizers, meanwhile you can work on this 👍
