### ISSUE TITLE
Improving the navbar

### ISSUE THREAD

**Issue by PranavChauhan22** [ALPHAVIO/WordNook#1001]
### Feature request-
Want to improve the navbar of wordnook
### Is your feature request related to a problem? Please describe. (optional)
-
### Describe the solution you'd like
I will add animations in it along with a little change in height and color schema

### Describe alternatives you've considered
-
### Describe how this feature will be useful to our readers.
Navbar gives user an insight about a prototype of website so making it appropriate helps user to navigate easily.
### Additional context
N/A
<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by PranavChauhan22** [comment]
assign me this issue under lgm-soc participant

**Comment by Pranav016** [comment]
> assign me this issue under lgm-soc participant

issue get assigned automatically when you comment the keyword.
Also can you be more specific about the issue ? What problem do you see in the navbar that you feel should be improved, some relevant screenshots could also help understand the issue.

**Comment by Pranav016** [comment]
comment again to reopen issue
