### ISSUE TITLE
Improving the footer

### ISSUE THREAD

**Issue by PranavChauhan22** [ALPHAVIO/WordNook#1002]
### Feature request-
Want to improve the footer,basically redesign it

### Is your feature request related to a problem? Please describe. (optional)
-
### Describe the solution you'd like
Redesign the footer,changing its color schema and adding animations in it.
### Describe alternatives you've considered
-

### Describe how this feature will be useful to our readers.
Footer is the basic element and its proper display is necessary for users.

### Additional context
N/A
<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by PranavChauhan22** [comment]
Assign me this issue under lgm-soc participant

**Comment by theBeginner86** [comment]
Hey @PranavChauhan22, can you be a little more specific about the type of animation and color scheme you are referring to.
- See, if you change the color scheme completely, then it might not fit with the rest of the color palette being used in the project
-  How animations in the footer would help the readers?
### If you could add a screen shot then it would be more clearer.

**Comment by Pranav016** [comment]
comment again to reopen issue
