### ISSUE TITLE
Remove text shadow in the footer text

### ISSUE THREAD

**Issue by supzi-del** [ALPHAVIO/WordNook#1012]
### Feature request-
The text shadow in the about WordNook text makes it hard to read

### Describe the solution you'd like
I would like to remove the shadow for a cleaner look and so as to match the other sections.

#### Are you contributing under any open-source program ?
LGM-SOC

<hr/>

**Comment by supzi-del** [comment]
`/assign`

**Comment by theBeginner86** [comment]
@supzi-del, Please don't remove the issue note while creating new issues.
