### ISSUE TITLE
add and move badges to the top

### ISSUE THREAD

**Issue by Umesh-01** [ALPHAVIO/WordNook#1016]
### Feature request-
I think badges should be at the top of README.md file. Here (see the image below) they are not looking good.

![image](https://user-images.githubusercontent.com/83420185/122441335-15697980-cfbb-11eb-9046-e1dc98ea71b5.png)

### Is your feature request related to a problem? Please describe. (optional)
No

### Describe the solution you'd like
I will move them to the top and also will add some more badges so that the README.md file will look more interactive and awesome. 

### Describe how this feature will be useful to our readers.
Since it will be colorful and more attractive than the text the user will like it and it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

#### Are you contributing under any open-source program ?
LGMSOC-21

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* It is adviced to take up/ work on only 2 issues at the same time.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Umesh-01** [comment]
@Pranav016 @AnanyaNegi should I work on this??

**Comment by Pranav016** [comment]
not required
