### ISSUE TITLE
Add a mailto: link from email in footer

### ISSUE THREAD

**Issue by supzi-del** [ALPHAVIO/WordNook#1034]
### Feature request-
When the user clicks on the email in the footer, it should redirect to the mailto: page

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe the solution you'd like
Adding a template link to the email
It should redirect to this page (example) : 
![Screenshot (298)](https://user-images.githubusercontent.com/78655439/123558099-38add900-d7b2-11eb-90fa-6898fcc36108.png)

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

#### Are you contributing under any open-source program ?
LGM-SOC

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* It is adviced to take up/ work on only 2 issues at the same time.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by supzi-del** [comment]
Hey! Can this issue be closed after merging PR?

**Comment by Pranav016** [comment]
> Hey! Can this issue be closed after merging PR?

Yes, after the PR gets merged.
