### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by srisatya1197** [ALPHAVIO/WordNook#1039]
Footer looks clumsy, I would like make it smooth by using icons and map for address section.
![SpacexMK - Google Chrome 30-06-2021 22_49_06](https://user-images.githubusercontent.com/78905067/124004510-b6155b80-d9f5-11eb-85e1-524459c22e14.png)

**Comment by theBeginner86** [comment]
Ok. But could you explain a bit more about how you would like to improve it?
If you could add the screenshots of the changes in the footer then that would be great!

Moreover, I would suggest you to not alter the issue template and make use of it to explain the changes/feature you want to add. 👍

**Comment by srisatya1197** [comment]
@theBeginner86 ok sure.

**Comment by srisatya1197** [comment]
@theBeginner86 Just I want to clear that I'll be inactive on github for a week(sem exams). I want to tell that if it's ok then will complete this  after a week.

**Comment by RiyaGupta89** [comment]
@theBeginner86 Hi, I can work on this issue. I will padding and stuff in footer so that it looks more clean which will enhance user experience of the website.

**Comment by theBeginner86** [comment]
@RiyaGupta89 Ok you can go ahead with a PR. If we like your changes in the footer section then we may merge it. 
We would be looking for some innovative ways of enhancing the overall look of the footer section but at the same time it must not change our current style.

**Comment by theBeginner86** [comment]
@srisatya1197 
Don't worry, start contributing once your are free. We would be happy to review your changes. 👍

**Comment by theBeginner86** [comment]
I would be closing this issue. As it is quite vague with the proposed changes.

@RiyaGupta89 @srisatya1197, Once you guys are ready then do raise an issue for the changes you want in the footer section. (Do follow the issue template while creating the issue and add screenshots as well). Then, I would review each of your issues, and we could discuss them separately. 👍
