### ISSUE TITLE
Add PSoC to open-source event list

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#1054]
### Feature request-
Add PSoC to open-source events associated with list.
You can take info from here- https://github.com/ALPHAVIO/Mirage-UI

LGM-SOC

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* It is adviced to take up/ work on only 2 issues at the same time.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Amrutha1101** [comment]
I would like to contribute to this issue under LGM-SOC

**Comment by Amrutha1101** [comment]
![IMG_20210710_090903](https://user-images.githubusercontent.com/63070698/125150592-8d603500-e15e-11eb-95bc-f1a282767757.jpg)
Is this the one you're talking about?

**Comment by Pranav016** [comment]
> ![IMG_20210710_090903](https://user-images.githubusercontent.com/63070698/125150592-8d603500-e15e-11eb-95bc-f1a282767757.jpg)
> Is this the one you're talking about?

Yes
