### ISSUE TITLE
Bug in the search feature on the home page

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/WordNook#1074]
### **Describe the bug**
The search bar on the home page must search for the blogs which we have on our web app. Moreover, if there isn't any blog then there should be a popup which says: `No blogs are there. Would you like to compose one!` and then it should give links to composing the blog or signup page depending upon the status of the user, i.e whether they are signed in or not. 
But right now it is not searching anything and rather it shows an ejs view error. Basically, when the search bar is being used then the testimonial array becomes undefined and then that is causing some issue.
Look into it, solve the testimonial bug causing it to be undefined and then make the search bar functional.

### **To Reproduce**
1. Go to 'http://localhost:3000/'
3. Type something in the search bar
4. Click on 'search'
5. See an error

### **Expected behavior**
The search bar should be made functional so that it could search the available blogs and gives the user the one they are looking for. This should happen if the blogs are there. But if blogs are not there then a pop up should appear which says: `No blogs are there. Would you like to compose one!`. Also, it must have links to the compose route provided the user is already signed in or to signup route if the user is not signed in.

### **Screenshots**

https://user-images.githubusercontent.com/73700530/126861277-c4a15dd1-0e53-44d6-9100-69f54325d190.mov

### **Additional context**
Do discuss with us if you need more clarification or have any doubts. Also, you can raise multiple PRs for it as this issue could be a little bit longer to solve in a single PR. Also, make sure that each PR must have some functional part of the entire feature.

#### Are you contributing under any open-source program ?

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* It is adviced to take up/ work on only 2 issues at the same time.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by RakeshPotnuru** [comment]
@theBeginner86 
Can I work on this?

**Comment by theBeginner86** [comment]
> @theBeginner86
> Can I work on this?

Sure!! go ahead.
But first have a look at the note below to find out, how to assign the issue to you. 👍

**Comment by RakeshPotnuru** [comment]
@theBeginner86 
I fixed the issue, can you review it and do tell me if I need to change anything?
