### ISSUE TITLE
Bug in the cancel button of edit page

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/WordNook#1075]
### **Describe the bug**
Basically when a signed-in user goes to the `read-profile` route to edit the page then the `cancel button` is not working. This should be working because if a user changes their mind and doesn't want to edit their profile then they have to click on the `dashboard button` on the navbar to take them back to their profile page. But ideally, the cancel button should also do the same thing.

### **To Reproduce**
1. Go to 'http://localhost:3000/read-profile'
2. Click on 'cancel'
4. Nothing happens

### **Expected behavior**
When the user clicks on the `cancel` button then the button should take the user back to the dashboard route.

### **Screenshots**

https://user-images.githubusercontent.com/73700530/126861559-d66b7f7a-ff41-4aa7-b35d-c1a3f105c807.mov

#### Are you contributing under any open-source program ?

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* It is adviced to take up/ work on only 2 issues at the same time.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by aashimawadhwa** [comment]
please assign this issue to me

**Comment by theBeginner86** [comment]
> Can I work on this ?
> Please assign it to me .

Please read the note at the end of the issue description, you'll get to know how to assign the issue to yourself. 🙂

**Comment by aashimawadhwa** [comment]
> > Can I work on this ?
> > Please assign it to me .
> 
> Please read the note at the end of the issue description, you'll get to know how to assign the issue to yourself. slightly_smiling_face

sorry I missed the note. thank you

**Comment by theBeginner86** [comment]
> > > Can I work on this ?
> > > Please assign it to me .
> > 
> > 
> > Please read the note at the end of the issue description, you'll get to know how to assign the issue to yourself. slightly_smiling_face
> 
> sorry I missed the note. thank you

no worries 👍. Carry on with the work.  😊
