### ISSUE TITLE
Application not opening

### ISSUE THREAD

**Issue by Asmit2952** [ALPHAVIO/WordNook#1098]
### **Describe the bug**
When I click the link to open the web app, an error page opens up saying "Application error".

### **To Reproduce**
1. Go to '[README.md](https://github.com/ALPHAVIO/WordNook#readme)'
2. Click on 'Visit Website'
3. See error

### **Expected behavior**
To open and navigate the web app

### **Screenshots**
![Screenshot (118)](https://user-images.githubusercontent.com/81866614/131253946-21918553-c2ff-466f-87d3-3d4cfb35fcf9.png)

### **Additional context**
NA

#### Are you contributing under any open-source program ?
NA

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* It is adviced to take up/ work on only 2 issues at the same time.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Pranav016** [comment]
@Asmit2952 Thank you for the concern, we'll work on it and it will be fixed very soon.

**Comment by Pranav016** [comment]
Issue resolved via #1100

**Comment by Pranav016** [comment]
@Asmit2952 Let me know if it is working fine now

**Comment by Asmit2952** [comment]
@Pranav016 Yess👍🏻...works perfectly fine
