### ISSUE TITLE
Add reply section to Comments

### ISSUE THREAD

**Issue by bitaashna** [ALPHAVIO/WordNook#229]
The comment section does not have a reply section. We can add it.
As a participant of GSSOC'21 ,I would to contribute to it.
can u please assign it to me.

**Comment by Pranav016** [comment]
You can work on two issues at a time, I'll assign you the third one after your first two get merged 👍

**Comment by Riya764** [comment]
Can l work on this issue?as a part of GSSoC' 21

**Comment by Sakshi0401** [comment]
As a participant of GSSOC'21 ,I would to contribute to it.
can u please assign it to me?

**Comment by anushree71199** [comment]
I would like to contribute to this issue as a part of GSSoc '21, Can you please assign it to me?

**Comment by nikhilgupta2001** [comment]
As a participant of GSSOC'21 ,I would like to contribute to it.
can u please assign it to me?

**Comment by shudhanshu03** [comment]
@bitaashna  Its been 5 days , Are you still working on this task or should I assign to someone else ? @Pranav016 Have a look once

**Comment by bitaashna** [comment]
yep @shudhanshu03 ! i am working on it. just give me one more day I'll submit it.

**Comment by shudhanshu03** [comment]
> yep @shudhanshu03 ! i am working on it. just give me one more day I'll submit it.

Okay No Problem .

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant. could you please assign me this?

**Comment by AnanyaNegi** [comment]
> 
> 
> I would like to contribute as a Gssoc21 participant. could you please assign me this?

it has been assigned to you. You can start working. All the best.

**Comment by Abhishekkr93** [comment]
Thanks for update!

**Comment by Navyasingla1309** [comment]
I am willing to contribute to this as GSsoc'21 participant. Can you please assign this to me?

**Comment by AnanyaNegi** [comment]
@Abhishekkr93  status?

**Comment by Abhishekkr93** [comment]
@AnanyaNegi  yes mam , I'm working on it but there is
my midsemm exam , so therefore delay in making pr. Can you please give me some days , I'll fix this.

**Comment by AnanyaNegi** [comment]
> 
> 
> @AnanyaNegi yes mam , I'm working on it but there is
> my midsemm exam , so therefore delay in making pr. Can you please give me some days , I'll fix this.

Okay.

**Comment by Furquan712** [comment]
I would like to work on this , Will you assignee me

**Comment by Ayush0730** [comment]
@Pranav016 I think for this issue we must have a separate comments model, currently comments is just an array inside post model.

Should I raise an issue to create comments model?

**Comment by Pranav016** [comment]
> @Pranav016 I think for this issue we must have a separate comments model, currently comments is just an array of data inside post model, Instead we could have array of ids of comment
> 
> Should I raise an issue to create comments model?

Yes you can
