### ISSUE TITLE
I would like to add rating and sharing feature.Can you please assign me this task under GSSOC'21 particiant?

### ISSUE THREAD

**Issue by AakankshaShah** [ALPHAVIO/WordNook#254]

**Comment by RushanKhan1** [comment]
Hi @AakankshaShah, Can you please provide a detailed description of your issue by preferably filling out the headings in the issue template.

**Comment by shudhanshu03** [comment]
/gssoc/

**Comment by AakankshaShah** [comment]
@RushanKhan1 
Sir ,I would like to add a feature that will allow users to share their blogs via whatsapp , facebook , instagram and other such social platforms.Also I would like to give a rating feature where we can give stars rating  to blogs.

**Comment by AnanyaNegi** [comment]
Hi, @AakankshaShah the rating/like feature is being handled in a different issue. However, if you would like to contribute to the sharing feature, I can assign this Issue to you.

**Comment by AakankshaShah** [comment]
@AnanyaNegi  Yes ma'am sure.
