### ISSUE TITLE
Add a Newsletter in Contact Us!!

### ISSUE THREAD

**Issue by bhubesh757** [ALPHAVIO/WordNook#276]
### Describe the solution you'd like
Newsletter makes the user friendly , it directly sends the blog posts daily in which part they interested in

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

Note:  
If you want to work on an issue, you should check if it has already been assigned to anyone. If the issue is free you can comment `/assign` to get the issue assigned to you.  
If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.  
Then you can directly start working on the issue.

**Comment by Pranav016** [comment]
Do you want to develop a form on contact page and use a mailing API for the periodic mails. Can you elaborate your idea more ?

**Comment by shudhanshu03** [comment]
/gssoc/

**Comment by bhubesh757** [comment]
@Pranav016 If We Create The Newsletter , Each Blog will Reach To the Subscribers Through the mail , By using The Mailchimp 
Does anybody is willing to contribute

**Comment by zhcet19** [comment]
I would love to work upon it as a GSSOC' 2021 participant but would you please specify it in more detail for clarification

**Comment by PrernaSingh587** [comment]
Is this issue still being worked upon?

**Comment by AnanyaNegi** [comment]
@ambivert-sam status?

**Comment by ambivert-sam** [comment]
> @ambivert-sam status?

working on it

**Comment by ambivert-sam** [comment]
> @ambivert-sam status?

Sorry ma'am you can assign it to someone else

**Comment by tanishq-arya** [comment]
Can you please explain what is to be done exactly in this issue ? @AnanyaNegi

**Comment by AnanyaNegi** [comment]
> 
> 
> /assign

are you working on this issue?

**Comment by Pranav016** [comment]
> @Pranav016 Could you please explain me a bit about this issue in detail?
> I believe that we want to add members (basically the users who login into our website) to the mailing list (i.e., under the audience tab of MailChimp account) of MailChimp APIs. So is that all or we also have to design UI/contents of mail and make it in a way that it is send to the users periodically.
> Also, let me know what should be the account details of MailChimp Account.

get alphavio's google credentials from me on discord and use it for mailchimp. Basically send one or two blogs (only if blogs are present - keep this edge case in mind) that have most likes or most views every month to the user who signed up for the newsletter.

**Comment by theBeginner86** [comment]
> > @Pranav016 Could you please explain me a bit about this issue in detail?
> > I believe that we want to add members (basically the users who login into our website) to the mailing list (i.e., under the audience tab of MailChimp account) of MailChimp APIs. So is that all or we also have to design UI/contents of mail and make it in a way that it is send to the users periodically.
> > Also, let me know what should be the account details of MailChimp Account.
> 
> get alphavio's google credentials from me on discord and use it for mailchimp. Basically send one or two blogs (only if blogs are present - keep this edge case in mind) that have most likes or most views every month to the user who signed up for the newsletter.
> 
> Also i think having a separate page all about newsletter would be better.

Okay, I will try to do that. I have asked for the credentials on discord.
