### ISSUE TITLE
Auto merge PRs from all-contributors bot

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#323]
### Feature request-
Add a GitHub action that automatically merges PRs from all-contributors bot.
Also let us know if you're working under GSSoC

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level0- 2 days
level1- 3 days
level2- 4 days
level3- 5 days
```

**Comment by promaroy** [comment]
Can I work on this as a part of GSSOC '21?
/assign

**Comment by Ankita297** [comment]
https://github.com/marketplace/actions/pr-merge-bot

**Comment by Ankita297** [comment]
Sir is this okay ?

**Comment by Ankita297** [comment]
https://github.com/pascalgn/automerge-action

**Comment by Ankita297** [comment]
@Pranav016  you want like when you add the label automerge  the  github action will be triggered and it will merge the PR  to master branch ?

**Comment by Pranav016** [comment]
> @Pranav016 you want like when you add the label automerge the github action will be triggered and it will merge the PR to master branch ?

No we had that before, but that is kind of the same as merging manually. You still have to go to the PR and add the label.
What I want is any PR received from @all-contributors bot should be merged automatically.

**Comment by Ankita297** [comment]
@Pranav016  can we do it like we target pull request and check if github.actor is allcontributors then we add the  the github action 
to auto add label of automerge

**Comment by Pranav016** [comment]
> @Pranav016 can we do it like we target pull request and check if github.actor is allcontributors then we add the the github action
> to auto add label of automerge

Yes we can

**Comment by Ankita297** [comment]
okay Sir . I  will try .

**Comment by Ankita297** [comment]
@Pranav016  This can be used ?
https://github.com/marketplace/actions/merge-me

**Comment by Ankita297** [comment]
@Pranav016  what should i write in github Login in above ?

**Comment by Pranav016** [comment]
> @Pranav016 This can be used ?
> https://github.com/marketplace/actions/merge-me

This works using CI this it will require tests or checks before merging automatically. We haven't added any tests yet..

**Comment by Ankita297** [comment]
but if i provide any username like Ankita297 then it merges automatically

**Comment by Ankita297** [comment]
![fdv by Ankita297 · Pull Request #82 · Ankita297_Story - Google Chrome 23-03-2021 10_26_16](https://user-images.githubusercontent.com/67833077/112095301-3f7cec80-8bc2-11eb-9274-f29f425b73aa.png)

**Comment by Ankita297** [comment]
@Pranav016

**Comment by Ankita297** [comment]
![fdv by Ankita297 · Pull Request #82 · Ankita297_Story - Google Chrome 23-03-2021 10_29_14](https://user-images.githubusercontent.com/67833077/112095526-ab5f5500-8bc2-11eb-9646-c7f3b78fab03.png)

**Comment by Ankita297** [comment]
@Pranav016  can we add github action  to automerge the PR from deoendabot  as not it is manully merged  .
Can you see my approach if it is right then may i raise the issue ?

**Comment by Ankita297** [comment]
@Pranav016 can we add github action to automerge the PR from dependabot as not it is manully merged .
Can you see my approach if it is right then may i raise the issue ?

**Comment by Ankita297** [comment]
![done by Ankita297 · Pull Request #6 · Ankita297_Story - Google Chrome 17-04-2021 21_28_32](https://user-images.githubusercontent.com/67833077/115119032-01f26000-9fc4-11eb-92e9-b753cce3f425.png)

**Comment by Ankita297** [comment]
This github action will only be triggered when there is dependencies label  which will be added by dependabot .
I don't know whether triage-bot will produce any hinderance So can you guide me .

**Comment by Ankita297** [comment]
@Pranav016 @AnanyaNegi ?

**Comment by Ankita297** [comment]
@Pranav016 ?

**Comment by Pranav016** [comment]
Sorry my notifications have been off for the past couple of days due to exams hence didn't reply..
The issue is regarding merging the all-contributors bot PRs right ? You're working on merging dependency updates..  @Ankita297

**Comment by Ankita297** [comment]
@Pranav016  i know this issue is for all contributors bot but  am asking for dependbot as current you are merging them manually .
If it is okay then i can raise the issue for  dependabot .
But i have doubt regarding triage bot .

**Comment by Pranav016** [comment]
> @Pranav016 i know this issue is for all contributors bot but am asking for dependbot as current you are merging them manually .
> If it is okay then i can raise the issue for dependabot .
> But i have doubt regarding triage bot .

earlier I had raised an issue for dependabot but we have decided not to automate it since we want to check compatibility % of the dependency before merging..

No, triage bot label won't affect it..

**Comment by Ankita297** [comment]
@Pranav016 okay so we have to add it manually only .

**Comment by Ankita297** [comment]
![docs_ add Ankita297 as a contributor by allcontributors · Pull Request #17 · Ankita297_New - Google Chrome 26-04-2021 22_16_02](https://user-images.githubusercontent.com/67833077/116120310-06fa9200-a6dd-11eb-90fd-d3d0506515a7.png)
