### ISSUE TITLE
add 'Testimonials' section to the website.

### ISSUE THREAD

**Issue by ainy-123** [ALPHAVIO/WordNook#342]
### Feature request-
I want to add a feature,i.e, testimonials section which will be like a proof of having good content on this website provided by the readers.

### Is your feature request related to a problem? Please describe. (optional)
yes.

### Describe alternatives you've considered
Alternatives to it can be a review/comments section.
 
### Describe how this feature will be useful to our readers.
It will be useful to the readers ,because, going  through different testimonials ,one can understand that how much this blog is useful to the reader and thus can effectively get an insight about whether to read or not in very less time with the help of other's reviews.
I am a GSSOC'21 participant.I want to work on this issue.('/assign')
kindly assign this to me.

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by ainy-123** [comment]
'/assign'

**Comment by ainy-123** [comment]
thanks for assigning me this issue.I will try my best to close this issue by the deadline.

**Comment by abhishek7997** [comment]
Please assign me the issue if the previous assignee is not able to complete it. @ainy-123

**Comment by Pranav016** [comment]
I feel that there could be vulgar things that could be put in the testimonials, how would you tackle that ?

**Comment by ainy-123** [comment]
> Also, note that only an authenticated user will be able to add a testimonial
> I feel that there could be vulgar things that could be put in the testimonials, how would you tackle that ?
> Some delete button or something ?

Yes sir , I will try to make it password protected or accessible to only authentic members by some other means.
I have not yet thought about these things,but yes,we can use a delete button for this case.

**Comment by Pranav016** [comment]
> > Also, note that only an authenticated user will be able to add a testimonial
> > I feel that there could be vulgar things that could be put in the testimonials, how would you tackle that ?
> > Some delete button or something ?
> 
> Yes sir , I will try to make it password protected or accessible to only authentic members by some other means.
> I have not yet thought about these things,but yes,we can use a delete button for this case.

Yes, take your time and let me know the plan before implementing 👍

**Comment by ainy-123** [comment]
> > > Also, note that only an authenticated user will be able to add a testimonial
> > > I feel that there could be vulgar things that could be put in the testimonials, how would you tackle that ?
> > > Some delete button or something ?
> > 
> > 
> > Yes sir , I will try to make it password protected or accessible to only authentic members by some other means.
> > I have not yet thought about these things,but yes,we can use a delete button for this case.
> 
> Yes, take your time and let me know the plan before implementing 👍

Sure sir !!

**Comment by AnanyaNegi** [comment]
@ainy-123 are you still working on the issue?

**Comment by tanishq-arya** [comment]
Can I work on this ? I am thinking of a modal ui { 3 in one row } in before the footer. Please assign me this under gssoc.

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/114589459-4d93c980-9ca5-11eb-9377-f450ffc48434.mp4

**Comment by Ankita297** [comment]
@Pranav016  I have created ui for testimonial . Is it okay ?

**Comment by Ankita297** [comment]
@Pranav016  ?

**Comment by AnanyaNegi** [comment]
> @Pranav016 ?
Hi @Ankita297 , @Pranav016  is busy for a few days due to exams, he will review when he gets free. Here is my review for the time being. 
I think the UI looks good. Just some points to add-
* Is it a auto carousel? This wasn't clear in the video. 
* Check for the responsiveness.

**Comment by Ankita297** [comment]
Yes it is an auto-carousel . I have added it with bootstrap . I am asking that i Have to do only frontend part

**Comment by Ankita297** [comment]
@AnanyaNegi ?

**Comment by AnanyaNegi** [comment]
> 
> 
> @AnanyaNegi ?

If you only want to do frontend, that's fine too.

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/115102544-2836e200-9f69-11eb-98a4-a65330b1e1b0.mp4

**Comment by Ankita297** [comment]
@Pranav016  @AnanyaNegi is it okay  Can i make the PR .But i have not added the backened .

**Comment by Ankita297** [comment]
@Pranav016 @AnanyaNegi is it okay Can i make the PR .But i have not added the backened .

**Comment by AnanyaNegi** [comment]
> @Pranav016 @AnanyaNegi is it okay Can i make the PR .But i have not added the backened .

Nw. You can make the pr. Will review it.
