### ISSUE TITLE
Using Docker in the project

### ISSUE THREAD

**Issue by jain-rishabh-21** [ALPHAVIO/WordNook#365]
### Feature request-
We can use Docker to build the project so that the new contributors don't find any difficulty in setting up dev environment irrespective of their OS.

### Is your feature request related to a problem? Please describe. (optional)
Problems while setting in different OS.

### Describe alternatives you've considered
Using Docker

### Describe how this feature will be useful to our readers.
Useful for Devs

### Additional context

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by jain-rishabh-21** [comment]
/assign 
If issue is found useful
Discord Username: krackerzzz#4371

**Comment by Pranav016** [comment]
The issue is useful but I feel right now a lot of beginners are contributing and dockerizing the project would make it more difficult for them. I'd suggest this issue should be re-raised after some time..

Closing issue for now, reopen if required.

**Comment by Pranav016** [comment]
I think we can add it as an additional feature that those who know docker and want to use the project from a container can pull the image from docker hub.

**Comment by Pranav016** [comment]
You can add a docker file and create account for Alphavio on docker hub and put the image there for anyone to use. ( you can take alphavio credentials from me on discord )
Then you can add that info to README.

Let me know if this sounds good.

**Comment by jain-rishabh-21** [comment]
Hey, you can assign it to me! Will do it!

**Comment by Pranav016** [comment]
> Hey, you can assign it to me! Will do it!

Its already assigned to you..

**Comment by jain-rishabh-21** [comment]
Yes please add the level tag too

**Comment by Pranav016** [comment]
> Yes please add the level tag too

Level tag not required in issues.

**Comment by Pranav016** [comment]
> You can add a docker file and create account for Alphavio on docker hub and put the image there for anyone to use. ( you can take alphavio credentials from me on discord )
> Then you can add that info to README.
> 
> Let me know if this sounds good.

Working on this ? @jain-rishabh-21

**Comment by jain-rishabh-21** [comment]
Hey, Yes will do it soon!
Sorry for the delay

**Comment by subhangi2731** [comment]
@Pranav016 can you please assign this issue to me

**Comment by Pranav016** [comment]
> @Pranav016 can you please assign this issue to me

Read the note under the issue

**Comment by subhangi2731** [comment]
@AnanyaNegi please assign me this issue I want to work on this
