### ISSUE TITLE
Add instructions in README for lock file version 2

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#497]
### Feature request-
A lot of PRs are changing package-lock.json file mainly because their system has older npm. Add instructions to README such that everybody can check their npm version and upgrade it for lock file version 2 to maintain consistency.

People with lock file version 1 remove some data from package-lock whereas those with version 2 add some data..
Links- https://nodejs.org/en/download/releases/

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by RituCs** [comment]
Hello, I would like to contribute on this issue under GSSoC'21. Please assign me.
