### ISSUE TITLE
Improper Alignment of Content in footer

### ISSUE THREAD

**Issue by Naman-1234** [ALPHAVIO/WordNook#522]
### Feature request-
Content is not looking properly aligned.

### Is your feature request related to a problem? Please describe. (optional)
Please refer screenshot:
![Screenshot (46)](https://user-images.githubusercontent.com/63748249/113060330-1ebe2380-91ce-11eb-86d5-1010faec8adb.png)

### Describe the solution you'd like
Proper Alignment

### Describe alternatives you've considered
Alignment of all the text properly.

### Describe how this feature will be useful to our readers.
Will improve UI.

### Additional context

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by raks924** [comment]
can i work on this issue?
m a GSSOC'21 participant
