### ISSUE TITLE
Changing the units from px to rems/ems

### ISSUE THREAD

**Issue by satcasm** [ALPHAVIO/WordNook#557]
In some files the styling is done using ```px```.
Would like to change it to ```rems/ems``` to keep the site responsive under GSSOC' 21.
Thanks!

**Comment by Pranav016** [comment]
@satcasm Can you please resolve your previous issues first ?
a lot of them are assigned, resolve or unassign them..

**Comment by satcasm** [comment]
@Pranav016 as my previous issues were not given ```reviewed``` label , I thought it was not  necessary for the project. Should I start working on them too?

**Comment by Pranav016** [comment]
> @Pranav016 as my previous issues were not given `reviewed` label or any `level` tag , I thought it was not necessary for the project. Should I start working on them too?


Yes, all issues are important, you can't leave the older ones. On issues only GSSoC label is enough.

**Comment by prajjwal1231** [comment]
Hey @Pranav016 How can i contribute in this issue. Do I have to wait for satcasm ?

**Comment by Pranav016** [comment]
> Hey @Pranav016 How can i contribute in this issue. Do I have to wait for satcasm ?

Yes, you can work..

**Comment by satcasm** [comment]
Hey @Pranav016 , it's been a week and the issue is still unresolved can I take on this issue again?
Thanks!

**Comment by Pranav016** [comment]
One last chance for @prajjwal1231 
Coz last time the CSS files were rearranged so I halted his PR..

**Comment by prajjwal1231** [comment]
Hey,
@Pranav016 I have done the changes properly and the conflict is coming up from prettifier BOT . If there is some more changes required so pls brief me about it.

& sry i have thought that this issue have been resolved after my commit. That is why I forgot to check this issue.

**Comment by Pranav016** [comment]
@prajjwal1231 can you make PR otherwise I think satcasm is willing to work on this..
