### ISSUE TITLE
No validation while updating profile

### ISSUE THREAD

**Issue by priyanshu20** [ALPHAVIO/WordNook#569]
### **Describe the bug**
When updating our profile there is lack of validation like the one that exists while signing up

### **To Reproduce**
1. Go to /read-profile
2. update username to an already existing username
3. click on save changes 

![image](https://user-images.githubusercontent.com/59313375/113472405-ad59cb80-9480-11eb-8621-9a9e48da9325.png)

### **Expected behavior**
Validation similar to that when signing up should be applied.

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by priyanshu20** [comment]
@Pranav016 we can also modularize the validation system so that we do not have to re write all the validations.
That might be a different longer issue and I can work on it if that is something we need.

**Comment by Pranav016** [comment]
> @Pranav016 we can also modularize the validation system so that we do not have to re write all the validations.
> That might be a different longer issue and I can work on it if that is something we need.

yes, sounds good. You can make a new issue for that and tag that issue here that they are inter dependent and that issue needs to be solved first before this one.

you can work on making middleware or functions for the validation systems..

**Comment by Pranav016** [comment]
@priyanshu20 can this issue be solved asap ?

**Comment by Ayush0730** [comment]
> @priyanshu20 can this issue be solved asap ?

Can I fix this?

**Comment by Pranav016** [comment]
> > @priyanshu20 can this issue be solved asap ?
> 
> Can I fix this?

I'll assign it to you if he doesn't reply withing 24hrs..

**Comment by priyanshu20** [comment]
Making a PR soon.

**Comment by Ayush0730** [comment]
> > > @priyanshu20 can this issue be solved asap ?
> > 
> > 
> > Can I fix this?
> 
> I'll assign it to you if he doesn't reply withing 24hrs..

Okay, So I am self assigning this as @priyanshu20 removed their assignment

**Comment by Pranav016** [comment]
> > > > @priyanshu20 can this issue be solved asap ?
> > > 
> > > 
> > > Can I fix this?
> > 
> > 
> > I'll assign it to you if he doesn't reply withing 24hrs..
> 
> Okay, So I am self assigning this as @priyanshu20 removed their assignment

How many issues are you assigned to?

**Comment by Ayush0730** [comment]
I tried fixing this using middleware, but it is creating error, because the original callback is executing in all cases, even if I dont return next() from the middleware, I think it is due to the callback function being async.

@Pranav016 Please give me some solution if you can, 

I am thinking of just validating the data in the callback itself instead of using middleware.

**Comment by Pranav016** [comment]
> I tried fixing this using middleware, but it is creating error, because the original callback is executing in all cases, even if I dont return next() from the middleware, I think it is due to the callback function being async.
> 
> @Pranav016 Please give me some solution if you can,
> 
> I am thinking of just validating the data in the callback itself instead of using middleware.

You mean the control gets to callback even before the data is validated right?
I checked the middleware again and it seems fine to me, idk why it is doing that. 
So as we know the callbacks are asynchronous so maybe it is not waiting for the middleware to run. A couple solutions I can think of based on the code I saw in the middleware-
* The middleware doesn't have async-await, so as it is performing if-else conditions, callback gets called. So I feel await will can help wait for some response before calling the callback. So add `async-await` to middleware.
* Try using `promises`, it can help make async code act synchronously
Something I am not sure, just thought about it but you can consider-
* call middleware from within the callback and await for its response
* use setTimeout

**Comment by Pranav016** [comment]
![image](https://user-images.githubusercontent.com/54665036/115679797-949e5080-a370-11eb-9204-c1f7a641d736.png)

**Comment by Pranav016** [comment]
So which method worked for you for solving this issue ?
