### ISSUE TITLE
Add steps to lint in README

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#613]
### Feature request-
Add detailed steps for the participants to lint their code before making their PR.
You can check the corresponding commands for linting from `package.json` under `scripts` object.
Please take this issue if you have relevant knowledge 👍 

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by ANSHIKA1806** [comment]
@Pranav016  I want to work on this issue. Please assign this to me.

**Comment by Pranav016** [comment]
will be solved via #728

**Comment by Ayush0730** [comment]
Do we need to add steps in Readme or contributing.md (contribution guidelines)?

**Comment by Pranav016** [comment]
> Do we need to add steps in Readme or contributing.md (contribution guidelines)?

Add it to README since it will be the first thing new contributors will check. Adding it to contributing.md is optional
