### ISSUE TITLE
hover effect on social media icons

### ISSUE THREAD

**Issue by soulsurya** [ALPHAVIO/WordNook#620]
### Feature request-
I want to add hover effects on social media icons at footer of your blog to make it more attractive.

### Describe the solution you'd like
I would like to add some cool hover animations on the icons.

### Describe how this feature will be useful to our readers.
this feature will make your site more attractive.

### Additional context
I'm working under GSSoC'21 so kindly assign me this issue under GSSoC'21 tag
/assign

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by aditidewangan** [comment]
Hello, I am GSSOC'21 participant I would like to work on this issue please /assign me.

**Comment by SachindraFernando** [comment]
Can I work on this issue?

**Comment by AnanyaNegi** [comment]
> 
> 
> Can I work on this issue?

This issue has been assigned to you. You can start working on it.

**Comment by SachindraFernando** [comment]
Done ma'am. Please review.
