### ISSUE TITLE
ReCaptcha Implementation

### ISSUE THREAD

**Issue by osamamagdy** [ALPHAVIO/WordNook#642]
I am a GSSoC 2021 participant and I would like to work on this issue.

### Feature request-
Adding ReCAPTCH I am not a robot to the website during sign-up

### **Describe the problem**
The Website is extremely exposed to the danger of spamming it with various sign-up requests 

### Describe the solution you'd like
I will implement Google ReCAPTCHA at the sign-up process to prevent spamming of the signing up an account

### Describe how this feature will be useful to our readers.
It protects the website from crashing by easily famous spamming technologies.

<hr/>

**Note:**
* Do mention if you are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto-assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
Still working on this ? @osamamagdy

**Comment by osamamagdy** [comment]
Yes, i have some exams so i will come back to it after that

**Comment by satcasm** [comment]
@Pranav016 is the issue still active?

**Comment by Pranav016** [comment]
> @Pranav016 is the issue still active?

yes

**Comment by satcasm** [comment]
Hey @Pranav016 , while commiting I am getting this error:
![image](https://user-images.githubusercontent.com/56315878/119640696-7e375900-be36-11eb-81b3-49bc4897966c.png)
How can I resolve this?

**Comment by Pranav016** [comment]
> Hey @Pranav016 , while commiting I am getting this error:
> ![image](https://user-images.githubusercontent.com/56315878/119640696-7e375900-be36-11eb-81b3-49bc4897966c.png)
> How can I resolve this?

what is your npm version ?

**Comment by satcasm** [comment]
I am currently using ```7.13.0```

**Comment by Pranav016** [comment]
https://github.com/npm/cli/issues/1845
refer to this thread to resolve the issue otherwise I'll try to solve it..

**Comment by satcasm** [comment]
@Pranav016 I went through the thread, but sadly nothing makes sense to me.I tried a thing or two mentioned there but no luck.
Let me know if you have any ideas.

**Comment by Pranav016** [comment]
> @Pranav016 I went through the thread, but sadly nothing makes sense to me.I tried a thing or two mentioned there but no luck.
> Let me know if you have any ideas.

Ok, I'll work on it when I am free..

**Comment by satcasm** [comment]
Hey @Pranav016 did you had any time to look into it?

**Comment by satcasm** [comment]
@Pranav016 , I tried this:(after reading how to comment in .json file online)
![image](https://user-images.githubusercontent.com/56315878/119867283-57af1600-bf3b-11eb-9d00-fb5c69523419.png)
But I am still getting the same error, now I am quite confused as to how husky is running even after commenting out.
Let me know if I did something wrong.

**Comment by Pranav016** [comment]
> @Pranav016 , I tried this:(after reading how to comment in .json file online)
> ![image](https://user-images.githubusercontent.com/56315878/119867283-57af1600-bf3b-11eb-9d00-fb5c69523419.png)
> But I am still getting the same error, now I am quite confused as to how husky is running even after commenting out.
> Let me know if I did something wrong.

![image](https://user-images.githubusercontent.com/54665036/119867946-0fdcbe80-bf3c-11eb-8670-aec2923bcf61.png)

**Comment by satcasm** [comment]
That's strange, cause I am getting this:
![image](https://user-images.githubusercontent.com/56315878/119876164-36ebbe00-bf45-11eb-8009-0ebb20d2a80e.png)

**Comment by Pranav016** [comment]
> That's strange, cause I am getting this:
> ![image](https://user-images.githubusercontent.com/56315878/119876164-36ebbe00-bf45-11eb-8009-0ebb20d2a80e.png)

Remove the Code, I'll fix it later

**Comment by Pranav016** [comment]
@all-contributor please add @osamamagdy for code

**Comment by Pranav016** [comment]
@all-contributors please add @osamamagdy for code
