### ISSUE TITLE
Functionality to remove image once uploaded

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#662]
### Feature request-
Add functionality to remove image once uploaded for the blog post.
(Once uploaded, we can only replace but not remove an image)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by abhishek96k** [comment]
I would like to work on this issue. As part of `gssoc21`

**Comment by Pranav016** [comment]
@abhishek96k working on this ? Should add a demo to explain this issue better or did you get it ?

**Comment by farseenmanekhan1232** [comment]
Can I work on this issue

**Comment by farseenmanekhan1232** [comment]
Instead of completely removing the profile , we can replace the profile with a default profile picture , just like in whatsapp or any other social media. 
If that is what you want , please let me implement the feature

**Comment by Pranav016** [comment]
> Instead of completely removing the profile , we can replace the profile with a default profile picture , just like in whatsapp or any other social media.
> If that is what you want , please let me implement the feature

No, I was talking about the image you upload while posting a blog. checkout issue description 🙂

**Comment by Ayush0730** [comment]
@Pranav016 I am thinking of adding a button similar to profile image delete button. Will that be okay?

**Comment by Ayush0730** [comment]
@Pranav016 please check this while you're online

> @Pranav016 I am thinking of adding a button similar to profile image delete button. Will that be okay?

**Comment by Pranav016** [comment]
> @Pranav016 I am thinking of adding a button similar to profile image delete button. Will that be okay?

Ok
