### ISSUE TITLE
Navbar isn't responsive

### ISSUE THREAD

**Issue by MennaMagdy2019** [ALPHAVIO/WordNook#706]
### **Describe the bug**
Navbar isn't responsive

### **Expected behavior**
I will modify the navbar and make it responsive to screen devices

### **Screenshots**
![jornal1](https://user-images.githubusercontent.com/50016070/115188250-f0ed4000-a0e4-11eb-9cdd-dc8e42737d24.JPG)
![jornal2](https://user-images.githubusercontent.com/50016070/115188255-f185d680-a0e4-11eb-9b4c-b82b61b6fbc4.JPG)

**Comment by MennaMagdy2019** [comment]
Can I work on this bug, please? @Pranav016

**Comment by Pranav016** [comment]
@MennaMagdy2019 Sure, you can work on making the navbar responsive for tablet view..

**Comment by Pranav016** [comment]
/gssoc/

**Comment by RushanKhan1** [comment]
@MennaMagdy2019 Hey, are you still working on this issue?

**Comment by subhangi2731** [comment]
@Pranav016 please assign this issue to me

**Comment by RushanKhan1** [comment]
> @Pranav016 please assign this issue to me
Hey @shubhangi2731, @Liri-s29 commented first so the issue is his.

**Comment by Liri-s29** [comment]
@RushanKhan1 The issue is solved already, I visited the site and it was not there.

**Comment by RushanKhan1** [comment]
> @RushanKhan1 The issue is solved already, I visited the site and it was not there.

Yes, you're right it's fixed, closing this.
