### ISSUE TITLE
Improve blog post UI

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#712]
### Feature request-
Improve styling of the information displayed in the blog post.
Make their colors consistent, add some padding since they look so compact, maybe add them in bootstrap pills or any styling of choice.
![image](https://user-images.githubusercontent.com/54665036/115294941-d6fc3d80-a176-11eb-952d-a2315a0b6eee.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
Complete one of the other two issues to get this one assigned. Try to have at most 2 assigned at a time

**Comment by anniesaxena** [comment]
Hi can you please assign me this issue? I am GSSOC'21 participant.

**Comment by anniesaxena** [comment]
I have made some changes in the styling. Can you please approve if this works?

![screencapture-localhost-3000-posts-6080254d827e000e840cf70a-2021-04-27-20_44_44](https://user-images.githubusercontent.com/54598906/116267476-112e9600-a79a-11eb-992b-9b822cefe21f.png)

@Pranav016

**Comment by anniesaxena** [comment]
@Pranav016 can you please confirm these changes

**Comment by Pranav016** [comment]
Keep likes and comments together and then views separately. Add them in boxes or styled bootstrap pills

**Comment by RushanKhan1** [comment]
@anniesaxena Hey, are you still working on this?

**Comment by Ayush0730** [comment]
> @anniesaxena Hey, are you still working on this?

If not, you can assign me
