### ISSUE TITLE
Text not visible due to background and font color

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#717]
### **Describe the bug**
I think at a lot of places in the website the text is not super clear. Add a white outline to all the text in the website. Make sure to reuse classes wherever necessary and write clean css.
![image](https://user-images.githubusercontent.com/54665036/115317487-497e1500-a199-11eb-80cb-fa29b87d3d0a.png)

### **To Reproduce**
1. Login
1. Click on Dashboard
1. Click on edit info
1. See the bug

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
Do you want something like this ? 
![image](https://user-images.githubusercontent.com/77333275/115697738-755bef00-a381-11eb-8e21-20e9041535bd.png)

**Comment by Pranav016** [comment]
> Do you want something like this ?
> ![image](https://user-images.githubusercontent.com/77333275/115697738-755bef00-a381-11eb-8e21-20e9041535bd.png)

This is still a little bit less visible, reduce the border size or try another color that makes the text more visible.

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/115698174-f6b38180-a381-11eb-81b4-3fbf5c95833d.png)

**Comment by tanishq-arya** [comment]
In this I have added a font weight.

**Comment by Pranav016** [comment]
I am looking at this images from phone so I won't be able to judge that good, I'd leave it upto you since you are viewing from laptop.
If it the text is more clearer than before then you can go ahead with it or try different stuff 👍

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/115698713-8d803e00-a382-11eb-8f93-a8be67f2c41d.png)

**Comment by tanishq-arya** [comment]
I have tried this color should we use it for text ? it is a darker variant and we won't have to add any outline or shadow.

**Comment by tanishq-arya** [comment]
> I am looking at this images from phone so I won't be able to judge that good, I'd leave it upto you since you are viewing from laptop.
> If it the text is more clearer than before then you can go ahead with it or try different stuff 👍

I'll keep on trying for something else too.

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/115699434-4777aa00-a383-11eb-980a-ff98f3ddfda2.png)

**Comment by tanishq-arya** [comment]
Also I was thinking the text is too small in the form. This is 1.5rem

**Comment by Pranav016** [comment]
@tanishq-arya working on this ?

**Comment by tanishq-arya** [comment]
Yes I am. Please take a look at the above ss I increased the size and changed the color so should I proceed with this or do something else.

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/115699434-4777aa00-a383-11eb-980a-ff98f3ddfda2.png)

This one.

**Comment by tanishq-arya** [comment]
@Pranav016 I tried this one too, If we use a darker shade to text-shadow the previous color.
![image](https://user-images.githubusercontent.com/77333275/116505818-7b9a2000-a8d9-11eb-99a1-df1b52949097.png)

**Comment by Pranav016** [comment]
> @Pranav016 I tried this one too, If we use a darker shade to text-shadow the previous color.
> ![image](https://user-images.githubusercontent.com/77333275/116505818-7b9a2000-a8d9-11eb-99a1-df1b52949097.png)

Keep the 3D effect to the minimal so you can keep x-y-z of the shadow either 0 or 1px. 
I think anything with white would look better since it will match the aesthetic of the website

**Comment by tanishq-arya** [comment]
I tried with white too but because of the background the white is not very clear.

**Comment by Pranav016** [comment]
> I tried with white too but because of the background the white is not very clear.

Ok so we can work with black but this shadow is giving a 3D effect.
Try this if it looks fine
`text-shadow: 0 0 1px black`

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/116507706-7212b700-a8dd-11eb-9911-6cd06b60ff46.png)
![image](https://user-images.githubusercontent.com/77333275/116507732-80f96980-a8dd-11eb-9e8b-e80d23b54973.png)

**Comment by tanishq-arya** [comment]
We have to decide for this part only the above text looks good for both.

**Comment by Pranav016** [comment]
Are you working on this issue? If yes, you can make a PR with this 
![image](https://user-images.githubusercontent.com/54665036/118135795-0d994100-b421-11eb-8eac-3f195c12fd2e.png)
