### ISSUE TITLE
Add badges to README for GitHub apps installed

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#729]
Let me know if anyone wants to work on this with me/ can make better badges than me. I'll let you know the applications

**Comment by Pranav016** [comment]
Add badges for prettier, all-contributors and PR triage

**Comment by aditisneh** [comment]
I am interested in working for the badges, but can you provide more detail regarding this. @Pranav016

**Comment by Pranav016** [comment]
> I am interested in working for the badges, but can you provide more detail regarding this. @Pranav016

You have to make badges, check the ones already there in the README

**Comment by aditisneh** [comment]
![project-badges](https://user-images.githubusercontent.com/56735634/115887325-710dff80-a46f-11eb-8b0b-e9af1c78cb94.png)
Are you taking about these badges right?

**Comment by Pranav016** [comment]
> ![project-badges](https://user-images.githubusercontent.com/56735634/115887325-710dff80-a46f-11eb-8b0b-e9af1c78cb94.png)
> Are you taking about these badges right?

Yeah but we'll need custom badges for the apps that have been installed on this particular repo

**Comment by hardikshah197** [comment]
May I take up this issue, If no one is working on it?
@RushanKhan1

**Comment by RushanKhan1** [comment]
> May I take up this issue, If no one is working on it?
> @RushanKhan1

Sure, you can comment `\assign` under issues with no assignees to assign the issue to yourself.

**Comment by Pranav016** [comment]
Add some badges for 
- Prettier bot
- Triage bot
- Imgbot
- All-contributors bot

**Comment by saloni-15** [comment]
If the badges are still needed, I have created some badges for the apps mentioned above

![image](https://user-images.githubusercontent.com/75828760/129184814-e2f27454-0d8f-460c-b5b6-730fc34d7788.png)

If these badges are suitable then I would like to add them to README.

@Pranav016 @theBeginner86  @Ayush0730
