### ISSUE TITLE
Add git-hooks using husky to check for commit messages

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#733]
### Feature request-
Add git-hooks using husky to check for commit messages.
We can use regex in it to check commit messages.
Commit style guide we plan to adapt - https://www.conventionalcommits.org/en/v1.0.0/ 

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by srrathi** [comment]
@AnanyaNegi I want to work on this issue. Please consider assigng it to me.

**Comment by AnanyaNegi** [comment]
> @AnanyaNegi I want to work on this issue. Please consider assigng it to me.

This issue has been assigned to you. All the best!

**Comment by RushanKhan1** [comment]
@srrathi Are you still working on this issue?

**Comment by srrathi** [comment]
No I'm sorry I'm not working on it please assign it to someone else.

**Comment by nishihere19** [comment]
Can I work on this under gssoc'21?

**Comment by Pranav016** [comment]
This one is solved.
