### ISSUE TITLE
Navigation bar size is big when scroll 

### ISSUE THREAD

**Issue by SamikshaSankar** [ALPHAVIO/WordNook#740]
We can make shrink  navigation bar when the user starts to scroll the page.

**Comment by Pranav016** [comment]
Can you add some illustration/ screenshot of the problem so that I can see it's a valid issue

**Comment by Pranav016** [comment]
You shouldn't have removed the template and should've filled it..

**Comment by SamikshaSankar** [comment]
> Can you add some illustration/ screenshot of the problem so that I can see it's a valid issue

Yeah..Wait

**Comment by SamikshaSankar** [comment]
> You shouldn't have removed the template and should've filled it..

No no I m just saying when we scroll we can make shrink bar..that`s it

**Comment by Pranav016** [comment]
The navbar looks fine to me
