### ISSUE TITLE
Update Banner in README.md

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#745]
### Feature request-
Update the banner or design a new banner for the project with name `WordNook`

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by aditisneh** [comment]
I can add a banner / gif. I am quite good at this :)

**Comment by Pranav016** [comment]
@aditisneh still working on this ?

**Comment by gargijs** [comment]
![WordNook](https://user-images.githubusercontent.com/63464238/117462531-64f46880-af6c-11eb-8e88-ec57303d5808.png)

please check the banner for PR.

**Comment by Pranav016** [comment]
I can kind of see some boundary of the new name being pasted there..

**Comment by Pranav016** [comment]
I think you can design a new one without the logo since the logo is also being changed then we would need a new banner after that..

**Comment by gargijs** [comment]
So I have to design a new banner without a logo?

**Comment by gargijs** [comment]
Okay,if I remove the pasted one then I can give the PR.

**Comment by aanchalrakheja** [comment]
I would want to work on this.

**Comment by gargijs** [comment]
I am already working on this @aanchalrakheja,it is already assigned to me and I have given the PR which will close this issue.
