### ISSUE TITLE
Design a new logo for the website

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#746]
### Feature request-
Design a new logo for the website and delete the older ones from assets folder that have `BlogSite` name in them. Design new ones with name `WordNook`.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by aditisneh** [comment]
Hey, I want to design the logo for the website. I you say , I'll post the logo design here itself after I am assigned.

**Comment by Pranav016** [comment]
> Hey, I want to design the logo for the website. I you say , I'll post the logo design here itself after I am assigned.

Check the note in the PR description 🙂
You can get the issue assigned by just commenting a keyword..

**Comment by Pranav016** [comment]
> Hey, I want to design the logo for the website. I you say , I'll post the logo design here itself after I am assigned.

I'll assign it for now but you can get it assigned like this as well 🙂 
![image](https://user-images.githubusercontent.com/54665036/115972676-72bded00-a56d-11eb-9fa6-418f1efa10dc.png)

**Comment by aditisneh** [comment]
@Pranav016 Okay thanks, first I am working on banner thing, will make a PR by tonight, then will work on logo.

**Comment by Pranav016** [comment]
> @Pranav016 Okay thanks, first I am working on banner thing, will make a PR by tonight, then will work on logo.

Yes sure, take your time :)

**Comment by NipuniKodithuwakku** [comment]
can I work on this issue?

**Comment by aditisneh** [comment]
![logo](https://user-images.githubusercontent.com/56735634/116716727-b6917600-a9f5-11eb-8b66-eaab252a98e0.png)
We can choose any of these for logo, let me know for any changes.

**Comment by Pranav016** [comment]
> ![logo](https://user-images.githubusercontent.com/56735634/116716727-b6917600-a9f5-11eb-8b66-eaab252a98e0.png)
> We can choose any of these for logo, let me know for any changes.

Sorry for the late reply..
This one looks good but the title will be `WordNook` instead of `Blogsite`
![image](https://user-images.githubusercontent.com/54665036/116803390-cb285800-ab34-11eb-8e0d-44185c2644b2.png)

This one also looks good and unique
![image](https://user-images.githubusercontent.com/54665036/116803400-f14df800-ab34-11eb-86de-a8769635d1d3.png)


I think second one is good and you can make a PR with it, make sure to delete all the old `BlogSite` logo's before adding this to the folder and to the website.
Check two folders for old blogsite logos- `assets` and `public/images`.

**Comment by aanchalrakheja** [comment]
would like to work on this issue.

**Comment by Pranav016** [comment]
> would like to work on this issue.
 
ok

**Comment by Pranav016** [comment]
@aanchalrakheja can i see some logo samples soon since we need to update the logo on the website urgently

**Comment by aditisneh** [comment]
@Pranav016 can i make a PR

> > ![logo](https://user-images.githubusercontent.com/56735634/116716727-b6917600-a9f5-11eb-8b66-eaab252a98e0.png)
> > We can choose any of these for logo, let me know for any changes.
> 
> Sorry for the late reply..
> This one looks good but the title will be `WordNook` instead of `Blogsite`
> ![image](https://user-images.githubusercontent.com/54665036/116803390-cb285800-ab34-11eb-8e0d-44185c2644b2.png)
> 
> This one also looks good and unique
> ![image](https://user-images.githubusercontent.com/54665036/116803400-f14df800-ab34-11eb-86de-a8769635d1d3.png)
> 
> I think second one is good and you can make a PR with it, make sure to delete all the old `BlogSite` logo's before adding this to the folder and to the website.
> Check two folders for old blogsite logos- `assets` and `public/images`.

@Pranav016 can I make a PR with the second logo. 
Apologies as my semester exams were going on.

**Comment by aanchalrakheja** [comment]
@Pranav016 Sure will get ready with some designs by tomorrow.

**Comment by Pranav016** [comment]
> @Pranav016 can i make a PR
> 
> > > ![logo](https://user-images.githubusercontent.com/56735634/116716727-b6917600-a9f5-11eb-8b66-eaab252a98e0.png)
> > > We can choose any of these for logo, let me know for any changes.
> > 
> > 
> > Sorry for the late reply..
> > This one looks good but the title will be `WordNook` instead of `Blogsite`
> > ![image](https://user-images.githubusercontent.com/54665036/116803390-cb285800-ab34-11eb-8e0d-44185c2644b2.png)
> > This one also looks good and unique
> > ![image](https://user-images.githubusercontent.com/54665036/116803400-f14df800-ab34-11eb-86de-a8769635d1d3.png)
> > I think second one is good and you can make a PR with it, make sure to delete all the old `BlogSite` logo's before adding this to the folder and to the website.
> > Check two folders for old blogsite logos- `assets` and `public/images`.
> 
> @Pranav016 can I make a PR with the second logo.
> Apologies as my semester exams were going on.

Sad to hear that but you should've informed a bit earlier maybe. Now its upto Aanchal only whether she wants to work or give up the issue. I can't do anything here acc to the rules.

**Comment by aditisneh** [comment]
No problem but it's upto you, actually, whose logo design you prefer for your website.

**Comment by aanchalrakheja** [comment]
![logo1](https://user-images.githubusercontent.com/68388581/117981896-1885a000-b353-11eb-9850-27533328fd96.png)
![logo2](https://user-images.githubusercontent.com/68388581/117985767-9bf4c080-b356-11eb-9aa6-6221889f4cd0.png)
![logo3](https://user-images.githubusercontent.com/68388581/117986113-f2fa9580-b356-11eb-84bc-059894f6ec91.png)
These are some of the designs.If you finalize some, I will add some colors to them.

**Comment by aanchalrakheja** [comment]
![logo4](https://user-images.githubusercontent.com/68388581/118272675-988d4080-b4e0-11eb-92cf-d1de2c851925.png)
![logo5](https://user-images.githubusercontent.com/68388581/118272689-9b883100-b4e0-11eb-90cd-0a3c1f328ae6.png)
![logo 6](https://user-images.githubusercontent.com/68388581/118272700-9f1bb800-b4e0-11eb-9e64-4adc1318272a.png)
![logo7](https://user-images.githubusercontent.com/68388581/118273039-10f40180-b4e1-11eb-9b24-2706aaf84f65.png)

**Comment by Pranav016** [comment]
I like these 2
![image](https://user-images.githubusercontent.com/54665036/118337199-e762c680-b530-11eb-8b3e-6612b492e287.png)

![image](https://user-images.githubusercontent.com/54665036/118337205-ea5db700-b530-11eb-8706-8ae18b9a5da2.png)

But they have a black background so they might not look good in the navbar, can you remove their black background.
For example this one doesn't have any background - 
![image](https://user-images.githubusercontent.com/54665036/118337255-08c3b280-b531-11eb-94c3-f0fa475bbee4.png)

**Comment by aanchalrakheja** [comment]
Ya the background can be changed. I ll change that and get it approved once.

**Comment by aanchalrakheja** [comment]
![logo new 2](https://user-images.githubusercontent.com/68388581/118351001-13a13600-b577-11eb-8993-c2bdc3e68959.png)
![logo new 3](https://user-images.githubusercontent.com/68388581/118351002-156af980-b577-11eb-9b20-1aba302d8c0b.png)
![logo new 4](https://user-images.githubusercontent.com/68388581/118351008-1bf97100-b577-11eb-9e26-b403dda57681.png)
![logo new](https://user-images.githubusercontent.com/68388581/118351012-1e5bcb00-b577-11eb-91e5-afe6d3bcf407.png)
Something like these to match the aesthetics of the page.

**Comment by Pranav016** [comment]
> ![logo new 2](https://user-images.githubusercontent.com/68388581/118351001-13a13600-b577-11eb-8993-c2bdc3e68959.png)
> ![logo new 3](https://user-images.githubusercontent.com/68388581/118351002-156af980-b577-11eb-9b20-1aba302d8c0b.png)
> ![logo new 4](https://user-images.githubusercontent.com/68388581/118351008-1bf97100-b577-11eb-9e26-b403dda57681.png)
> ![logo new](https://user-images.githubusercontent.com/68388581/118351012-1e5bcb00-b577-11eb-91e5-afe6d3bcf407.png)
> Something like these to match the aesthetics of the page.

Let's go with the orange logo, I would like to get your suggestion to choose between the two. @RushanKhan1 @AnanyaNegi can also suggest which one is better

**Comment by aanchalrakheja** [comment]
> > ![logo new 2](https://user-images.githubusercontent.com/68388581/118351001-13a13600-b577-11eb-8993-c2bdc3e68959.png)
> > ![logo new 3](https://user-images.githubusercontent.com/68388581/118351002-156af980-b577-11eb-9b20-1aba302d8c0b.png)
> > ![logo new 4](https://user-images.githubusercontent.com/68388581/118351008-1bf97100-b577-11eb-9e26-b403dda57681.png)
> > ![logo new](https://user-images.githubusercontent.com/68388581/118351012-1e5bcb00-b577-11eb-91e5-afe6d3bcf407.png)
> > Something like these to match the aesthetics of the page.
> 
> Let's go with the orange logo, I would like to get your suggestion to choose between the two. @RushanKhan1 @AnanyaNegi can also suggest which one is better

I think the one with hand will look better.

**Comment by RushanKhan1** [comment]
> > ![logo new 2](https://user-images.githubusercontent.com/68388581/118351001-13a13600-b577-11eb-8993-c2bdc3e68959.png)
> > ![logo new 3](https://user-images.githubusercontent.com/68388581/118351002-156af980-b577-11eb-9b20-1aba302d8c0b.png)
> > ![logo new 4](https://user-images.githubusercontent.com/68388581/118351008-1bf97100-b577-11eb-9e26-b403dda57681.png)
> > ![logo new](https://user-images.githubusercontent.com/68388581/118351012-1e5bcb00-b577-11eb-91e5-afe6d3bcf407.png)
> > Something like these to match the aesthetics of the page.
> 
> Let's go with the orange logo, I would like to get your suggestion to choose between the two. @RushanKhan1 @AnanyaNegi can also suggest which one is better

I like the orange logo with the feather tip pen, looks simple and professional.

**Comment by Pranav016** [comment]
Lets go with the orange feather one!

**Comment by aanchalrakheja** [comment]
Ok. Will make a pr latest by tomorrow due to some urgency at my end.

**Comment by aanchalrakheja** [comment]
![image](https://user-images.githubusercontent.com/68388581/118527770-3aba5c00-b75f-11eb-8058-53db4b9141f4.png)
![image](https://user-images.githubusercontent.com/68388581/118527836-4c9bff00-b75f-11eb-8d25-d84c4f348440.png)
![image](https://user-images.githubusercontent.com/68388581/118527889-59b8ee00-b75f-11eb-90dc-3d1e04d0df33.png)
This is how it looks. Should I continue with it.

**Comment by RushanKhan1** [comment]
> ![image](https://user-images.githubusercontent.com/68388581/118527770-3aba5c00-b75f-11eb-8058-53db4b9141f4.png)
> ![image](https://user-images.githubusercontent.com/68388581/118527836-4c9bff00-b75f-11eb-8d25-d84c4f348440.png)
> ![image](https://user-images.githubusercontent.com/68388581/118527889-59b8ee00-b75f-11eb-90dc-3d1e04d0df33.png)
> This is how it looks. Should I continue with it.

It looks good to me 👍🏻

**Comment by RushanKhan1** [comment]
It looks good to me 👍🏻

**Comment by Pranav016** [comment]
> ![image](https://user-images.githubusercontent.com/68388581/118527770-3aba5c00-b75f-11eb-8058-53db4b9141f4.png)
> ![image](https://user-images.githubusercontent.com/68388581/118527836-4c9bff00-b75f-11eb-8d25-d84c4f348440.png)
> ![image](https://user-images.githubusercontent.com/68388581/118527889-59b8ee00-b75f-11eb-90dc-3d1e04d0df33.png)
> This is how it looks. Should I continue with it.

Looks good, I think we can now remove the WordNook text since it's already there in the logo. And make the logo a little bit bigger.

**Comment by ambivert-sam** [comment]
I'm a participant of GSSOC'21 can I work on this issue, please?

**Comment by aanchalrakheja** [comment]
![image](https://user-images.githubusercontent.com/68388581/118607974-d3d88980-b7d6-11eb-99da-3365b34171d5.png)
![image](https://user-images.githubusercontent.com/68388581/118608162-03879180-b7d7-11eb-9d9e-db966630db9b.png)
![image](https://user-images.githubusercontent.com/68388581/118608246-1b5f1580-b7d7-11eb-91a3-009c66c74318.png)
Like this?

**Comment by Pranav016** [comment]
> Should i continue with this?

Yes
