### ISSUE TITLE
Add a chatbot

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#751]
### Feature request-
Add a new chatbot to the website and remove the code for the old chatbot.
Since repo name was changed hence the API keys have changed. You can take the google credentials for ALPHAVIO's gmail account to use to make a chatbot wherever you like..

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by avanisingh0105** [comment]
Hi, I am new to this repo, would like get  ALPHAVIO's gmail account to use it to make a chatbot using landbot.io.

**Comment by Pranav016** [comment]
> Hi, I am new to this repo, would like get ALPHAVIO's gmail account to use it to make a chatbot using landbot.io.
> Open to suggestions , if any.

Ping me on discord for the credentials

**Comment by Pranav016** [comment]
Actually I just updated the repo link in Landbot.io and our previous bot has started working again. I think we can continue with that..
Sorry for the inconvenience, I appreciate your interest in the project and would encourage to take up more issues 🙂

**Comment by Pranav016** [comment]
![image](https://user-images.githubusercontent.com/54665036/116015746-1257aa00-a658-11eb-83f3-6a55c49acbd8.png)

**Comment by avanisingh0105** [comment]
Good to know that the chatbot started working but why does it still say "Unfortunately, I am not available right now?"
Isn't a complete working chatbot required ?

**Comment by Pranav016** [comment]
> Good to know that the chatbot started working but why does it still say "Unfortunately, I am not available right now?"
> Isn't a complete working chatbot required ?

I think the number of request we can send to the chatbot crossed the limit. I can give you the credentials and you can check and work on it if there is any issue there..

**Comment by avanisingh0105** [comment]
Do we have the subscription to Landbot ? (As it is a paid service ) If not then I can research about some free chatbots available (if any) and then use that in our project.

**Comment by Pranav016** [comment]
> Do we have the subscription to Landbot ? (As it is a paid service ) If not then I can research about some free chatbots available (if any) and then use that in our project.

Yes it is paid and we don't have subscribtion. You can look for free ones..

**Comment by avanisingh0105** [comment]
> > Do we have the subscription to Landbot ? (As it is a paid service ) If not then I can research about some free chatbots available (if any) and then use that in our project.
> 
> Yes it is paid and we don't have subscribtion. You can look for free ones..

Sure, I will see if there are any free bot service and then get back here.

**Comment by avanisingh0105** [comment]
Hi, i found some free chatbots but they all were having 50-60 chats/month limitation.
