### ISSUE TITLE
Add sticky social icons in left of website

### ISSUE THREAD

**Issue by ShrutiOmer** [ALPHAVIO/WordNook#752]
### Feature request-
I can add  sticky social icons on the left of site.

### Describe how this feature will be useful to our readers.
along with social icons in the footer we can add them in the left side which will look more interactive and when user hover over them they will scale out.

### Additional context
I am a GSSoC'21 participant please assign this issue to me.
I have added this feature to a website and there its screenshot.
![image](https://user-images.githubusercontent.com/75009990/115987410-a4b56a80-a5d2-11eb-8e18-e5e6cf3a56c1.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
I appreciate for you showing interest in contributing to the project but this issue is not required right now since social icons are already present in the footer. And the website doesn't have any social accounts as of now so showing off our social icons really wouldn't matter.

But I would encourage you to raise more or take up any existing issues 👍 
Happy Learning !
