### ISSUE TITLE
Forgot/Reset password functionality

### ISSUE THREAD

**Issue by avanisingh0105** [ALPHAVIO/WordNook#760]
### Feature request-
Forgot/Reset password functionality

### Describe the solution you'd like
Forgot/Reset password button needs to be added

### Describe alternatives you've considered
No alternatives if the user forgets their password

### Describe how this feature will be useful to our readers.
If a user has forgot their password or just want to reset their password in any case.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
Make sure to write clean code for the backend of this issue 🙂

**Comment by avanisingh0105** [comment]
> Make sure to write clean code for the backend of this issue 🙂
Yes sure, as of now I am just a beginner in nodejs but i will give it my best shot, would be happy to come back to the discussion panel if i get stuck somewhere.

**Comment by avanisingh0105** [comment]
@Pranav016 I was having some issues with nodemailer-maligun-transport so i switched to Sendgrid(which offers 100mails/mo) for lifetime)  but then they are not sending me the apikey "due to some security issues" as per them. So can you setup sendgrid account using ALPHAVIO's gmail account and provide me with the API key so that i can complete this task.

**Comment by Pranav016** [comment]
> @Pranav016 I was having some issues with nodemailer-maligun-transport so i switched to Sendgrid(which offers 100mails/mo) for lifetime) but then they are not sending me the apikey "due to some security issues" as per them. So can you setup sendgrid account using ALPHAVIO's gmail account and provide me with the API key so that i can complete this task.

You can take ALPHAVIO's gmail credentials from me on discord 👍

**Comment by avanisingh0105** [comment]
Okay, how to find you on discord?

**Comment by Pranav016** [comment]
> Okay, how to find you on discord?

You can check wordbook channel on GSSoC's server and find my profile from there..

**Comment by avanisingh0105** [comment]
> > Okay, how to find you on discord?
> 
> You can check `wordnook` channel on GSSoC's server and find my profile from there..

I can't find you on discord as I am not a gssoc21 participant.

**Comment by Pranav016** [comment]
> > > Okay, how to find you on discord?
> > 
> > 
> > You can check `wordnook` channel on GSSoC's server and find my profile from there..
> 
> I can't find you on discord as I am not a gssoc21 participant.

Pranav#8006

**Comment by avanisingh0105** [comment]
> > > > Okay, how to find you on discord?
> > > 
> > > 
> > > You can check `wordnook` channel on GSSoC's server and find my profile from there..
> > 
> > 
> > I can't find you on discord as I am not a gssoc21 participant.
> 
> Pranav#8006

**Comment by avanisingh0105** [comment]
> > > > > Okay, how to find you on discord?
> > > > 
> > > > 
> > > > You can check `wordnook` channel on GSSoC's server and find my profile from there..
> > > 
> > > 
> > > I can't find you on discord as I am not a gssoc21 participant.
> > 
> > 
> > Pranav#8006
Check your friend request panel.Sent you request.

**Comment by subhangi2731** [comment]
@AnanyaNegi please assign this issue to me
