### ISSUE TITLE
Improve the `Write testimonial` button

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#770]
### Feature request-
Improve the `Write testimonial` button.
![image](https://user-images.githubusercontent.com/54665036/116505343-3f19f480-a8d8-11eb-8c42-825b814588f9.png)
Remove the black border and add a white border like this-
![image](https://user-images.githubusercontent.com/54665036/116505401-6ffa2980-a8d8-11eb-8650-f2970491f54f.png)

Also it should go blue on hover like the `READ MORE` button.
Make sure to reuse css classes and pre-made colors wherever possible.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/116507298-a174f400-a8dc-11eb-8732-eff231a405d8.png)

**Comment by tanishq-arya** [comment]
@Pranav016 should I reduce the font size it is looking very big in comparison

**Comment by tanishq-arya** [comment]
Something like this 
![image](https://user-images.githubusercontent.com/77333275/116508079-33c9c780-a8de-11eb-937c-d26d79365219.png)
