### ISSUE TITLE
Improve content and heading styles

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#771]
### Feature request-
Improve the content at the top of testimonials section and add styling to the `Testimonials` heading.
![image](https://user-images.githubusercontent.com/54665036/116505545-d5e6b100-a8d8-11eb-8219-19d8c62139b0.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
I like something like this would look good.
![image](https://user-images.githubusercontent.com/77333275/116509348-bf445800-a8e0-11eb-905c-d8a76e5bf760.png)

**Comment by Pranav016** [comment]
> I like something like this would look good.
> ![image](https://user-images.githubusercontent.com/77333275/116509348-bf445800-a8e0-11eb-905c-d8a76e5bf760.png)

No, the `Feel free to write` has to be replaced with a better headline, so content has to be changed and some text shadow etc to the heading that matches the aesthetic of the website

**Comment by tanishq-arya** [comment]
> > I like something like this would look good.
> > ![image](https://user-images.githubusercontent.com/77333275/116509348-bf445800-a8e0-11eb-905c-d8a76e5bf760.png)
> 
> No, the `Feel free to write` has to be replaced with a better headline, so content has to be changed and some text shadow etc to the heading that matches the aesthetic of the website

Okay I'll update you soon.

**Comment by tanishq-arya** [comment]
@Pranav016 Sorry for the delay. 
![image](https://user-images.githubusercontent.com/77333275/118145865-ae8cf980-b42b-11eb-916a-69c6b1aaf03f.png)

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/118154813-24499300-b435-11eb-8f05-9cc45dab1f4f.png)
@Pranav016 
Is this okay ? or should I increase the text. 
Like Here's what our users say about us.
Write a testimonial and spread the word.

**Comment by tanishq-arya** [comment]
@Pranav016 should I make a PR for this ? Or you want any changes.
