### ISSUE TITLE
Implement backend for testimonials page

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#773]
### Feature request-
Implement backend for testimonials page in `routes/testionials.router.js`.
* Add a new page to the website where the testimonials are visible. We'll have a button on the website that will lead to that page. Name that page as `Testimonial Wall`.
* Whenever a person submits a testimonial by clicking on the `Write Testimonial` button then he or she gets redirected to the testimonial wall where their testimonial will be visible.
* We haven't decided the deletion criteria for the testimonial so for now just add a delete button on each testimonial.

**This issue could be big so you can raise smaller issues under this and assign them to yourself to get more points for the whole feature**

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by theBeginner86** [comment]
@Pranav016 
Do you want me to add more features regarding this issue?
