### ISSUE TITLE
Add navigation buttons to testimonial carousel

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#777]
### Feature request-
Add left and right navigation buttons to testimonial carousel
![image](https://user-images.githubusercontent.com/54665036/116515733-4b0eb200-a8ea-11eb-9434-d9225dbc0159.png)

Also there is his very light carousel slide indicator that is not visible in white. Improve it so that it's visible
![image](https://user-images.githubusercontent.com/54665036/116515911-8dd08a00-a8ea-11eb-9bf1-1ae2cf8edf03.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/116728661-d0d25080-aa03-11eb-9f88-b5fd36f7d892.mp4

**Comment by Ankita297** [comment]
@Pranav016 is it okay ?
