### ISSUE TITLE
Issue with updating profile info

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#779]
### **Describe the bug**
I was trying to update my profile picture and on entering my old password this error was shown.
![image](https://user-images.githubusercontent.com/54665036/116538111-b9606e00-a904-11eb-897d-d3c388ccfc23.png)

![image](https://user-images.githubusercontent.com/54665036/116538079-afd70600-a904-11eb-90bf-b556d30968e9.png)

I think this is because of this new validation that was added in #765 that my old password is not passing.

### **To Reproduce**
1. Go to Dashboard
2. Click on update profile
3. Update some info
4. Enter Password and click save

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
As you have created your password when there was no password validation, so the password is invalid for now. But as you can see, no user can signup with invalid password now. So if you will delete the database and create a new one, this issue will be resolved. (or just change the password)

**Comment by Pranav016** [comment]
> As you have created your password when there was no password validation, so the password is invalid for now. But as you can see, no user can signup with invalid password now. So if you will delete the database and create a new one, this issue will be resolved. (or just change the password)

Yes true, I know the solution but how do fix it for other people who use their old accounts? Maybe I'll have to clear the DB

**Comment by Ayush0730** [comment]
I think we should implement changing password feature, like currently we can change our password without even knowing the old password. So i think we should have a verification to update password. To change password the user must enter his/her old password and then new password

**Comment by Ayush0730** [comment]
Then we can remove password validation from the old password and just validate the new password

**Comment by Pranav016** [comment]
> I think we should implement changing password feature, like currently we can change our password without even knowing the old password. So i think we should have a verification to update password. To change password the user must enter his/her old password and then new password

I think this feature can be done when forget password feature gets implementated.

**Comment by Ayush0730** [comment]
> > I think we should implement changing password feature, like currently we can change our password without even knowing the old password. So i think we should have a verification to update password. To change password the user must enter his/her old password and then new password
> 
> I think this feature can be done when forget password feature gets implementated.

Okay
