### ISSUE TITLE
Issue with sign-up route

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#780]
### **Describe the bug**
Not able to sign-up on the website.
Getting this error.
![image](https://user-images.githubusercontent.com/54665036/116538617-5fac7380-a905-11eb-92f2-b4488e9895a5.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
I am not getting this error on localhost, with image or without image

**Comment by Pranav016** [comment]
> I am not getting this error on localhost, with image or without image

Can you check once on the deployed website?
I am guessing its some issue with the DB then, I'll see into it today

**Comment by Pranav016** [comment]
> I am not getting this error on localhost, with image or without image

I am still getting this error, checked the database as well and updated everything still there seems to be some issue with sign-up

**Comment by GuptaTanisha** [comment]
Please assign this to me.

**Comment by RushanKhan1** [comment]
Hi @GuptaTanisha, are you still working on this issue?

**Comment by GuptaTanisha** [comment]
> Hi @GuptaTanisha, are you still working on this issue?

Yes, there is no such on running the app locally. I was unable to find the reason for the bug.

**Comment by GuptaTanisha** [comment]
> > Hi @GuptaTanisha, are you still working on this issue?
> 
> Yes, there is no such issue while running the app locally, issue exists only online. I was unable to find the reason the bug.

**Comment by Pranav016** [comment]
> > Hi @GuptaTanisha, are you still working on this issue?
> 
> Yes, there is no such on running the app locally. I was unable to find the reason for the bug.

Are you able to login to the deployed website ?

**Comment by GuptaTanisha** [comment]
> > > Hi @GuptaTanisha, are you still working on this issue?
> > 
> > 
> > Yes, there is no such on running the app locally. I was unable to find the reason for the bug.
> 
> Are you able to login to the deployed website ?

No sir

**Comment by GuptaTanisha** [comment]
May be we need to change the content headers to application/json as now they are something else.

**Comment by GuptaTanisha** [comment]
> May be we need to change the content headers to application/json.
Supporting documents:
[Bonsai Docs](https://docs.bonsai.io/article/303-api-error-422-unprocessable-entity)
![github](https://user-images.githubusercontent.com/64624412/118343498-0ff5bb00-b547-11eb-8d67-f86ba6ce6eaf.png)

**Comment by Pranav016** [comment]
> May be we need to change the content headers to application/json.
> Supporting documents:
> [Bonsai Docs](https://docs.bonsai.io/article/303-api-error-422-unprocessable-entity)
> The content-type at present is something else:-
> ![github](https://user-images.githubusercontent.com/64624412/118343498-0ff5bb00-b547-11eb-8d67-f86ba6ce6eaf.png)

Maybe yes, you could be right. We can only try. If you know how to do it, you can make a PR with that and I'll merge to test it. Otherwise I'll try to do this later when I get time.

**Comment by Ayush0730** [comment]
@Pranav016 Is this not fixed by #882?

**Comment by Pranav016** [comment]
> @Pranav016 Is this not fixed by #882?

No, I tried solving but it's still there

**Comment by subhangi2731** [comment]
@Pranav016 please assign this issue to me

**Comment by theBeginner86** [comment]
@Pranav016 is this issue still up?
I tried signing up through the Heroku link, and it did register the account successfully.

**Comment by Pranav016** [comment]
> @Pranav016 is this issue still up?
> I tried signing up through the Heroku link, and it did register the account successfully.

You mean you logged in successfully? Ok, you can give it a try if you were able to log in👍

**Comment by theBeginner86** [comment]
yeah, it did logged in successfully. I tried it again just now.

**Comment by Ayush0730** [comment]
@Pranav016 I tried this now on the deployed web app, its working fine, so I think we can close this

**Comment by Pranav016** [comment]
> @Pranav016 I tried this now on the deployed web app, its working fine, so I think we can close this

Check once again, I'm still getting the error

**Comment by theBeginner86** [comment]
Check this out:


- For signing up: 


https://user-images.githubusercontent.com/73700530/124243487-8f613d00-db3b-11eb-9f74-30b7452c9f1d.mp4



- For logging in (I had to make a new video because I forgot the email 😅)


https://user-images.githubusercontent.com/73700530/124242170-14e3ed80-db3a-11eb-9989-1d35ad0093a6.mov


But I feel that everything is working perfectly fine. 🙌👍
