### ISSUE TITLE
Addition of Testimonial Wall Page (Testimonial Backend Feature)

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/WordNook#787]
### Feature request-
Testimonial Wall is a page which will show all the testimonials given to our project.

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe the solution you'd like
For this, I made a page, Testimonial Wall which could be easily accessed from navbar. Then I used simple get requests to render the ejs files with the data of testimonials.

### Describe how this feature will be useful to our readers.
This would help to increase credibility of our project. Also will help the visitors to easily access it.

### Additional context
I m a GSSOC'21 participant and would like to work on it.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by theBeginner86** [comment]
<img width="1440" alt="Screenshot 2021-05-01 at 2 37 08 AM" src="https://user-images.githubusercontent.com/73700530/116770541-5dabf700-aa62-11eb-84d9-be829433088c.png">


The testimonial looks like this. 
Please tell is it fine for our projects. Or should I make some changes into the CSS.

**Comment by Pranav016** [comment]
> <img alt="Screenshot 2021-05-01 at 2 37 08 AM" width="1440" src="https://user-images.githubusercontent.com/73700530/116770541-5dabf700-aa62-11eb-84d9-be829433088c.png">
> 
> The testimonial looks like this.
> Please tell is it fine for our projects. Or should I make some changes into the CSS.

Add the testimonials in some bootstrap card components otherwise looks good

**Comment by theBeginner86** [comment]
ok I will try to do it.

**Comment by Pranav016** [comment]
> ok I will try to do it.

Or you can leave it to this we can have another issue to improve the UI of the testimonial page. It's totally up to you what you are comfortable with

**Comment by theBeginner86** [comment]
ok then I will make this into a PR. Then once the testimonial page works the way we want then we could improve its UI. Because I feel that we need to add the write testimonial feature also into it.
