### ISSUE TITLE
Improve share button style

### ISSUE THREAD

**Issue by Ayush0730** [ALPHAVIO/WordNook#790]
### Feature request-
Share button is just simple HTML button, improve its styles and make it like other buttons

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe the solution you'd like
Styles the button

### Describe how this feature will be useful to our readers.
Improve UI
### Additional context
![image](https://user-images.githubusercontent.com/68139755/116788070-4baf7000-aac5-11eb-86c3-b4906b3b2e84.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
I have multiple styles in my mind, please check and tell me which one suits best

1: 
![image](https://user-images.githubusercontent.com/68139755/116788832-71d70f00-aac9-11eb-95ce-9d47879a33d7.png)

2: This one is getting to the edge of the screen
![image](https://user-images.githubusercontent.com/68139755/116788867-a5b23480-aac9-11eb-8d35-ae9912cf3231.png)

3:
![image](https://user-images.githubusercontent.com/68139755/116788894-c5e1f380-aac9-11eb-9858-197812a2847c.png)

4:
![image](https://user-images.githubusercontent.com/68139755/116788943-02155400-aaca-11eb-8371-2b807772212f.png)

**Comment by Pranav016** [comment]
> I have multiple styles in my mind, please check and tell me which one suits best
> 
> 1:
> ![image](https://user-images.githubusercontent.com/68139755/116788832-71d70f00-aac9-11eb-95ce-9d47879a33d7.png)
> 
> 2: This one is getting to the edge of the screen
> ![image](https://user-images.githubusercontent.com/68139755/116788867-a5b23480-aac9-11eb-8d35-ae9912cf3231.png)
> 
> 3:
> ![image](https://user-images.githubusercontent.com/68139755/116788894-c5e1f380-aac9-11eb-9858-197812a2847c.png)
> 
> 4:
> ![image](https://user-images.githubusercontent.com/68139755/116788943-02155400-aaca-11eb-8371-2b807772212f.png)

I am not able to choose one between 2 and 4, you can make a PR with any button between 2 and 4
