### ISSUE TITLE
Allow Addition of New Testimonial (Implement backend for testimonials)

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/WordNook#792]
### Feature request-
Through this feature a logged in user would be able to add new testimonials to our project.

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe the solution you'd like
In-order to implement it, I added post request for the testimonial-wall page which takes the inputted views by the logged in person then store the full name and the inputted views as two objects at the end of the testimonial array which is already there in our project.
This basically adds new objects as new elements into the testimonial array. Then it gets rendered normally as other dummy testimonials are being rendered through the testimonial-wall.ejs file.

### Describe how this feature will be useful to our readers.
This will further add credibility and more functionality to our project

### Additional context
I m a GSSOC'21 participant and would like to work on it.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by theBeginner86** [comment]
@Pranav016 
I was not able to add the video because the size was large. So added it to google drive. 
https://drive.google.com/drive/folders/1q1-24nLjMVkc6ubHgTFur6gIzVC6cCZs?usp=sharing
Please check it and tell whether it is fine for our project.
Right now I have made the link to be viewed by everybody. So once you check it then please tell me then I would change it back to restricted.

**Comment by Pranav016** [comment]
@theBeginner86 assign yourself this issue by commenting the keyword otherwise someone else will assign it to them and I won't be able to help..

**Comment by Pranav016** [comment]
> @Pranav016
> I was not able to add the video because the size was large. So added it to google drive.
> https://drive.google.com/drive/folders/1q1-24nLjMVkc6ubHgTFur6gIzVC6cCZs?usp=sharing
> Please check it and tell whether it is fine for our project.
> Right now I have made the link to be viewed by everybody. So once you check it then please tell me then I would change it back to restricted. I m saying this to just be on the safer side for my drive and email related to it.

Great work, maybe have a button at the top of testimonial wall as well that will scroll down to the actual text-box because even from home page when we click on `Write testimonial` it goes to testimonial wall and you have to scroll which some people might not know that the text-box is at the end of the page.

You can do this by adding a id to the text box and then `href` to the new button that you will add to the testimonial page

**Comment by theBeginner86** [comment]
ok I will try to do that.
