### ISSUE TITLE
To add testimonials in the form of cards in testimonial-wall page

### ISSUE THREAD

**Issue by srrathi** [ALPHAVIO/WordNook#793]
### Feature request-
A clear and concise description of the feature.
To list all the the testimonials in the testimonial-wall page in the form of cards with cool design.

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 
As currently the testimonials are there in the form a list we can change them in the form of cards with 2 or 3 cards in a row. It will look much attractive.

### Describe the solution you'd like
To list all the the testimonials in the testimonial-wall page in the form of cards with cool design in the form of cards with 2 or 3 cards in a row. It will look much attractive.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.
Yes it will make the testimonials text much readable as currently the text is not going much well with the background and blending with it making it less readable and less attractive.

### Additional context

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by AshuKV** [comment]
Hi I am a GSSOC'21 participant. I want to work on this issue under GSSoC'21. Can you please assign it to me?

**Comment by srrathi** [comment]
Thanks @Pranav016 I'll start working on this asap now.

**Comment by srrathi** [comment]
@Pranav016 Can I add nodemon in it so that the page auto update whenever we change something in the code.

**Comment by Pranav016** [comment]
> @Pranav016 Can I add nodemon in it so that the page auto update whenever we change something in the code.

It already there, use command `npm run dev`

**Comment by srrathi** [comment]
Please have a look at it. Is it okay?
![image](https://user-images.githubusercontent.com/57089237/116820707-f42c0580-ab93-11eb-8d68-733474fc1b49.png)

**Comment by srrathi** [comment]
> @Pranav016 Please have a look at it. Is it okay?
> ![image](https://user-images.githubusercontent.com/57089237/116820707-f42c0580-ab93-11eb-8d68-733474fc1b49.png)

@Pranav016 Do I have to make some changes or I should send the PR?

**Comment by srrathi** [comment]
@Pranav016 I need your review and suggestions to move forward please review it.

**Comment by Pranav016** [comment]
I think this looks similar to the way we have our blogs, would've looked cooler if these were horizontal cards. But yes this also looks good and if you can add some animation to this then that would be even better.

These are just my thoughts, I could be wrong. I'd like hear from @AnanyaNegi @RushanKhan1 as well 👍

**Comment by srrathi** [comment]
> I think this looks similar to the way we have our blogs, would've looked cooler if these were horizontal cards. But yes this also looks good and if you can add some animation to this then that would be even better.
> 
> These are just my thoughts, I could be wrong. I'd like hear from @AnanyaNegi @RushanKhan1 as well +1

I'm sorry I don't get what you exactly mean by horizontal cards. If you explain a bit more I think I can make it as you wish. Yes I can add some animation in it. Will let you know about it.

**Comment by RushanKhan1** [comment]
> > I think this looks similar to the way we have our blogs, would've looked cooler if these were horizontal cards. But yes this also looks good and if you can add some animation to this then that would be even better.
> > These are just my thoughts, I could be wrong. I'd like hear from @AnanyaNegi @RushanKhan1 as well +1
> 
> I'm sorry I don't get what you exactly mean by horizontal cards. If you explain a bit more I think I can make it as you wish. Yes I can add some animation in it. Will let you know about it.

I think he's talking about something like [this](https://codepen.io/gatoledo1/pen/MWKpLNY). In my opinion, it would look good if you could make something like this along with right and left navigational buttons.

**Comment by Pranav016** [comment]
> > I think this looks similar to the way we have our blogs, would've looked cooler if these were horizontal cards. But yes this also looks good and if you can add some animation to this then that would be even better.
> > These are just my thoughts, I could be wrong. I'd like hear from @AnanyaNegi @RushanKhan1 as well +1
> 
> I'm sorry I don't get what you exactly mean by horizontal cards. If you explain a bit more I think I can make it as you wish. Yes I can add some animation in it. Will let you know about it.

Sorry, by horizontal cards I meant like full length cards with some animation

**Comment by srrathi** [comment]
> > > I think this looks similar to the way we have our blogs, would've looked cooler if these were horizontal cards. But yes this also looks good and if you can add some animation to this then that would be even better.
> > > These are just my thoughts, I could be wrong. I'd like hear from @AnanyaNegi @RushanKhan1 as well +1
> > 
> > 
> > I'm sorry I don't get what you exactly mean by horizontal cards. If you explain a bit more I think I can make it as you wish. Yes I can add some animation in it. Will let you know about it.
> 
> Sorry, by horizontal cards I meant cards with same width as the page with some animation

Yeah I can do that will update you soon about it.

**Comment by srrathi** [comment]
@Pranav016 Is it okay?

https://user-images.githubusercontent.com/57089237/117521306-bd5a5300-afca-11eb-92b2-a70ce170ea51.mp4

**Comment by srrathi** [comment]
> > @Pranav016 Is it okay?
> > Screencast.from.08-05-21.06.49.54.AM.IST.mp4
> 
> Yup, card design looks good+1
> I hope the color of the card looks better in real than in recording. It looks a little dull in the recording but yes card design is fine now

Yes, @Pranav016 Should I send the PR.

**Comment by Pranav016** [comment]
> > > @Pranav016 Is it okay?
> > > Screencast.from.08-05-21.06.49.54.AM.IST.mp4
> > 
> > 
> > Yup, card design looks good+1
> > I hope the color of the card looks better in real than in recording. It looks a little dull in the recording but yes card design is fine now
> 
> Yes, @Pranav016 Should I send the PR.

Yes

**Comment by srrathi** [comment]
@Pranav016 I've raised the PR please review it and if it's fine merge it.
