### ISSUE TITLE
"Remove profile image" feature

### ISSUE THREAD

**Issue by Ayush0730** [ALPHAVIO/WordNook#801]
### Feature request-
Add functionality to remove profile image

### Is your feature request related to a problem? Please describe. (optional)
Users are not able to remove their profile (only able to change it) 

### Describe the solution you'd like
Add functionality to remove profile image

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
Hey @Pranav016. While I was working on this issue, I noticed that on smaller screens profile image is looking very small.

As I was trying to add a delete button on the top of profile image

See these

On large Screens:
![image](https://user-images.githubusercontent.com/68139755/116910506-5bfd5180-ac63-11eb-83d7-b181ff55b274.png)

On mobile size:
![image](https://user-images.githubusercontent.com/68139755/116910557-6b7c9a80-ac63-11eb-833d-a266fac90383.png)


So, that's why, I was saying, should we make the profile image larger on smaller devices, like make it 25% on small devices and keep 10% on large??

**Comment by Ayush0730** [comment]
@Pranav016 Please review

**Comment by Pranav016** [comment]
Take advantage of units like `vh` or `vw` for making profile image suitable for small devices. And you can add the delete button on the side or something of the profile image instead of having it on the image but this way also it works.

**Comment by Pranav016** [comment]
> > Take advantage of units like `vh` or `vw` for making profile image suitable for small devices. And you can add the delete button on the side or something of the profile image instead of having it on the image but this way also it works.
> 
> I think delete button on image looks great
> 
> So, can I change the profile image size?
> 
> And should I do changes to profile image size in this PR of this issue or separate?

You can raise a new issue for it, solve that and come back to this one.
