### ISSUE TITLE
Updating the testimonial wall

### ISSUE THREAD

**Issue by PranavChauhan22** [ALPHAVIO/WordNook#804]
Why i want to work on this issue?
=> I want to update the testimonial wall as it looks static.
How i will do it?
=>I will change the background and some scroll animations with sticky background to add some extra featues.
A prototype from my website elaborating what i am going to do=>
<img width="1440" alt="Screenshot 2021-05-03 at 4 36 29 PM" src="https://user-images.githubusercontent.com/83133554/116869594-a3b5b600-ac2e-11eb-9643-37bd77fea4d9.png">

I request the admin or mentor to please grant me this issue...

**Comment by Pranav016** [comment]
Someone is working on styling the testimonial page in #793 hence cannot accept this issue
