### ISSUE TITLE
Responsiveness of navbar

### ISSUE THREAD

**Issue by satcasm** [ALPHAVIO/WordNook#809]
The links present on the navbar are hiding when we minimize the size of the screen.
Would like to work on it under GSSOC' 21.
Thanks!
Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/117021553-14370280-ad15-11eb-80ba-0a38da5850d9.png)

**Comment by Pranav016** [comment]
/gssoc/

**Comment by Pranav016** [comment]
#817
