### ISSUE TITLE
Changing the units from pxs to rems/ems

### ISSUE THREAD

**Issue by satcasm** [ALPHAVIO/WordNook#810]
While going through the ```css``` file , I noticed that there are some properties that uses ```px```, would like to change it to ```rems/ems``` such that the site remains responsive under GSSOC' 21.
Thanks!

**Comment by Pranav016** [comment]
Last time I checked things were responsive.
Some css had to have px values.
You can actually raise issue for the component that is not responsive and then fix its css.
