### ISSUE TITLE
Pre commit hooks not working

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#811]
### **Describe the bug**
The pre-commit hooks that I added in `package.json` file (using husky) that should run and lint the code before any commit, are not working. I want you to test and try to fix it so that it starts working,

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by satcasm** [comment]
Hey @Pranav016 I am not sure if I would be able to do this , but I still want to give it a shot . Can I take this issue?

**Comment by satcasm** [comment]
Hey @Pranav016 after going through this https://github.com/typicode/husky/issues/326,  I discovered that we need to set ```"husky": "^4.2.3"``` in the ```package.json``` for ```husky``` to work, but while doing so the ```package-lock.json``` file also gets modified. So, what to do?

**Comment by satcasm** [comment]
Moreover , the tests are failing:
![image](https://user-images.githubusercontent.com/56315878/117165296-fd5ee180-ade2-11eb-88ac-9a104f5cb29e.png)

**Comment by Pranav016** [comment]
> Hey @Pranav016 after going through this [typicode/husky#326](https://github.com/typicode/husky/issues/326), I discovered that we need to set `"husky": "^4.2.3"` in the `package.json` for `husky` to work, but while doing so the `package-lock.json` file changes drastically(half of code lines are removed). So, what to do?

Husky 6.0.0 already present as a dev dependency

Maybe we need at as a main dependency

**Comment by Pranav016** [comment]
> Moreover , the tests are failing:
> ![image](https://user-images.githubusercontent.com/56315878/117165296-fd5ee180-ade2-11eb-88ac-9a104f5cb29e.png)

I'll take care of these later

**Comment by satcasm** [comment]
> > Hey @Pranav016 after going through this [typicode/husky#326](https://github.com/typicode/husky/issues/326), I discovered that we need to set `"husky": "^4.2.3"` in the `package.json` for `husky` to work, but while doing so the `package-lock.json` file changes drastically(half of code lines are removed). So, what to do?
> 
> Husky 6.0.0 already present as a dev dependency
> 
> Maybe we need at as a main dependency.
> 
> Regarding lines removed, check your lockfile version or let me know your npm version.

Yeah, regarding the version of Husky I read in that issue I mentioned above, there are certain issues with the lastest versions, that's why it's not working. So, my best guess is we need to reduce the version.
My npm version is ```6.14.12``` is that causing the issue?

**Comment by Pranav016** [comment]
> > > Hey @Pranav016 after going through this [typicode/husky#326](https://github.com/typicode/husky/issues/326), I discovered that we need to set `"husky": "^4.2.3"` in the `package.json` for `husky` to work, but while doing so the `package-lock.json` file changes drastically(half of code lines are removed). So, what to do?
> > 
> > 
> > Husky 6.0.0 already present as a dev dependency
> > Maybe we need at as a main dependency.
> > Regarding lines removed, check your lockfile version or let me know your npm version.
> 
> Yeah, regarding the version of Husky I read in that issue I mentioned above, there are certain issues with the lastest versions, that's why it's not working. So, my best guess is we need to reduce the version.
> My npm version is `6.14.12` is that causing the issue with `lock` file?

Yes, you need npm version 7 and above for lockfile version 2.

And I'll check the issue link you attached above and will get back to you 👍

**Comment by Lukortech** [comment]
Yeah, I had to update npm to newer version. 
Works on 7.12.0

**Comment by Sukriti-sood** [comment]
@Pranav016 Can I try  ?

**Comment by Pranav016** [comment]
> @Pranav016 Can I try ? As much I know Imlementation of husky for higher versions has been changed that may be the reason.

Sure you can try.
But in a recent PR the pre commit hook was removed because a contributor was not able to commit so I suggested to remove them and I'll work on it later. So just add them back in the package.json file or let me know in case of any doubt.
