### ISSUE TITLE
Change position of testimonial-wall button

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#812]
### Feature request-
Remove testimonial wall button from the navbar and place it somewhere on the home page.
![image](https://user-images.githubusercontent.com/54665036/117039916-f07cb800-ad26-11eb-8317-da717c10d0d3.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by satcasm** [comment]
Hey @Pranav016 is this good enough?
![image](https://user-images.githubusercontent.com/56315878/117493229-56b84380-af90-11eb-837d-f2ba12e833a0.png)
Let me know if you have some other changes in mind.

**Comment by Pranav016** [comment]
I think an orange button right here would look good, coz in the pic above it's kind of mixing up with the utility buttons
![image](https://user-images.githubusercontent.com/54665036/117500486-5624aa80-af9a-11eb-8bb7-4ee46e713fe7.png)

**Comment by satcasm** [comment]
Thoughts abt this?
![image](https://user-images.githubusercontent.com/56315878/117549077-0e635900-b056-11eb-8c12-c8719bd5e7f2.png)

**Comment by satcasm** [comment]
Should I make ```Hi there!``` and the button inline?

**Comment by satcasm** [comment]
Or this is fine?
![image](https://user-images.githubusercontent.com/56315878/117549606-fd681700-b058-11eb-9cff-9ffe285be1de.png)

**Comment by Pranav016** [comment]
> Or this is fine?
> ![image](https://user-images.githubusercontent.com/56315878/117549606-fd681700-b058-11eb-9cff-9ffe285be1de.png)

This is fine👍

**Comment by satcasm** [comment]
Hey @Pranav016 have you made some changes to the ```husky``` ? I am getting this error while adding a commit:
![image](https://user-images.githubusercontent.com/56315878/117579448-7bd3c000-b110-11eb-9cf4-fbfaee931169.png)

**Comment by Pranav016** [comment]
> Hey @Pranav016 have you made some changes to the `husky` ? I am getting this error while adding a commit:
> ![image](https://user-images.githubusercontent.com/56315878/117579448-7bd3c000-b110-11eb-9cf4-fbfaee931169.png)

Pull the changes and try again
