### ISSUE TITLE
social icons enhacement 

### ISSUE THREAD

**Issue by Ankita297** [ALPHAVIO/WordNook#820]
### Feature request-
I want to enhance the hovering effect  and some other changes .
### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/117246547-7a796d80-ae5a-11eb-98d2-b630f66bbf16.mp4

**Comment by Ankita297** [comment]
@Pranav016 is this okay ?

**Comment by Pranav016** [comment]
> @Pranav016 then can i work on hover effect ?

Yes

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/117528101-24d5ca00-afee-11eb-8dbd-92137257adfa.mp4

**Comment by Ankita297** [comment]
![WordNook - Google Chrome 08-05-2021 11_10_53](https://user-images.githubusercontent.com/67833077/117528194-91e95f80-afee-11eb-9bee-15b4270aef30.png)
@Pranav016 is it okay can i make a PR for this ?

**Comment by Pranav016** [comment]
> ![WordNook - Google Chrome 08-05-2021 11_10_53](https://user-images.githubusercontent.com/67833077/117528194-91e95f80-afee-11eb-9bee-15b4270aef30.png)
> @Pranav016 is it okay can i make a PR for this ?

Check for responsiveness otherwise yes they look good

**Comment by Ankita297** [comment]
![WordNook - Google Chrome 08-05-2021 12_12_18](https://user-images.githubusercontent.com/67833077/117529710-b34e4980-aff6-11eb-9245-4ccc8a252986.png)
@Pranav016 should i make a new PR or do the changes in previous PR .
