### ISSUE TITLE
UI Enhancement of Landing Page

### ISSUE THREAD

**Issue by SpecTEviL** [ALPHAVIO/WordNook#827]
### Feature request-
The UI of the landing page looks a bit dull with the colour and effects. I would like to add some hover effects and improve on the colours unless they're from the theme. It would be under GSSoC21

### Is your feature request related to a problem? Please describe. (optional)
Not a problem.

### Describe the solution you'd like
The UI of the landing page looks a bit dull with the colour and effects. I would like to add some hover effects and improve on the colours unless they're from the theme.

### Describe alternatives you've considered
Would be adding some effects and rounding the border and stuff related to frontend enhancement.

### Describe how this feature will be useful to our readers.
The first impression is the last impression and one needs to see good effects and colours to their eyes which would make the user visit the site again when needed.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by SpecTEviL** [comment]
@Pranav016 can you please add the required level to this issue?

**Comment by Pranav016** [comment]
I'm cool with hover effects but I don't want the colors to be changed on the landing page since they are a part of a theme. But if you think you can make it better then go ahead, you change the color but show me some demo before making a PR for that.

**Comment by SpecTEviL** [comment]
Yes sure, will do that. Thanks @Pranav016!

> I'm cool with hover effects but I don't want the colors to be changed on the landing page since they are a part of a theme. But if you think you can make it better then go ahead, you change the color but show me some demo before making a PR for that.
