### ISSUE TITLE
Increase the gap between the various navbar options to distinguish between them clearly.

### ISSUE THREAD

**Issue by aanchalrakheja** [ALPHAVIO/WordNook#830]
### **Describe the bug**
Currently the navigation options such as home,about contact us etc seem a bit clustered and cannot be clearly distinguished at the first sight. So the gap between then can be adjusted a bit.

### **Screenshots**
![image](https://user-images.githubusercontent.com/68388581/117485489-0c31c980-af86-11eb-8194-08fadffd8389.png)

### **Additional context**

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by gargijs** [comment]
I want to work on this.

**Comment by Pranav016** [comment]
#812

**Comment by aanchalrakheja** [comment]
I wanted to work on this and so opened it, was waiting for it to get reviewed, I didn't have the idea that I have to assign it on my own. Can i work on it?

**Comment by aanchalrakheja** [comment]
@gargijs please look into it.

**Comment by Pranav016** [comment]
> Does #812 solve this ?

.

**Comment by gargijs** [comment]
But I have already worked on it.

**Comment by Pranav016** [comment]
> But I have already worked on it.

I asked a question right when you got the issue assigned and did not answer. Collect all the relevant info before working on the issue. and the PR has some mistakes
