### ISSUE TITLE
The logo of the site says blogSite, shouldn't it be updated with the new name

### ISSUE THREAD

**Issue by aanchalrakheja** [ALPHAVIO/WordNook#831]
### **Additional context**

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by gargijs** [comment]
I want to work on this

**Comment by Pranav016** [comment]
#746

**Comment by gargijs** [comment]
![Inkedissue 831_LI](https://user-images.githubusercontent.com/63464238/117498387-5bccc100-af97-11eb-84c9-a6c6a80d85c2.jpg)

**Comment by gargijs** [comment]
It is blogsite written in the logo.

**Comment by Pranav016** [comment]
> #746

.

**Comment by gargijs** [comment]
Okay
