### ISSUE TITLE
Improvement of pre loader of a website.

### ISSUE THREAD

**Issue by ritmojs** [ALPHAVIO/WordNook#835]
### Feature request-
Adding better pre loader.

**Comment by ritmojs** [comment]
I want to work on this issue under GSSOC21.
Please assign me this issue.

**Comment by Ankita297** [comment]
@Pranav016 Can i work on this ?

**Comment by ritmojs** [comment]
> @Pranav016 Can i work on this ?
I am already working on this issue.

**Comment by Ankita297** [comment]
okay @ritmojs .
