### ISSUE TITLE
Save or check email case insensitively

### ISSUE THREAD

**Issue by Ayush0730** [ALPHAVIO/WordNook#837]
### Feature request-
As we know emails are case insensitive, but currently in this project, email is verified case sensitively

### Is your feature request related to a problem? Please describe. (optional)
User may enter their email in different cases and will not be able to log in again, in case they enter it in incorrect case

### Describe the solution you'd like
check email case insensitively or save the emails in lower case only (***for that we need to clear database***)

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context
Close this issue, if not required

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ayush0730** [comment]
@Pranav016 Please review and tell me if this is required or not, and what should I do?

1. Check insensitively
2. Save in lowercase directly ( Needs to clear database )

**Comment by Pranav016** [comment]
I think saving it all in lower case would solve the issue.

**Comment by Ayush0730** [comment]
> I think saving it all in lower case would solve the issue.

But if we don't clear database, old ones will stay the same

**Comment by Pranav016** [comment]
> > I think saving it all in lower case would solve the issue.
> 
> But if we don't clear database, old ones will stay the same

I'll clear it
