### ISSUE TITLE
Adding remember me and forgot password in login form

### ISSUE THREAD

**Issue by AbhipsaGuru1012** [ALPHAVIO/WordNook#854]
### Feature request-
The login form doesn't  have a remember me and forgot password. I would like to add that.

### Describe the solution you'd like
I would like to add remember me and forgot password

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by AbhipsaGuru1012** [comment]
> Do you want to add the buttons only or the functionality as well ?

I will add the buttons and I will add another page for forgot password. For the remember me feature I will try to add the functionality

**Comment by Pranav016** [comment]
Ok👍

**Comment by AbhipsaGuru1012** [comment]
@Pranav016 I have made a PR. Please review. I will be making another PR for adding remember me functionality
