### ISSUE TITLE
Background of testimonial in home page

### ISSUE THREAD

**Issue by RuchiGitHu** [ALPHAVIO/WordNook#859]
### Feature request-
As each wall and piece of website has background color, I want to put background color in testimonial of home page so that it look like landing page of website.

### Describe the solution you'd like
Would like to add background color in testimonial.

### Describe alternatives you've considered
Na

### Describe how this feature will be useful to our readers.
After adding background color, that section of testimonial will not look different as of now.

### Additional context
![image](https://user-images.githubusercontent.com/71754179/118014616-06b2f580-b371-11eb-91dd-f80bd04ca928.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
Actually I wanted to have a different background of the testimonial carousel to make it look like a different section of the website

**Comment by RuchiGitHu** [comment]
> Actually I wanted to have a different background of the testimonial carousel than the rest of the website to make it look like a different section of the website.
> If the motive of this issue is something different then do comment to reopen the issue. Closing it for now.

I were saying this only, wanted to change the background of testimonial in the home page so that the testimonial looks good and also the slides of each testimonial look more readable and visible...

**Comment by Pranav016** [comment]
This issue is different from #864 right?

**Comment by RuchiGitHu** [comment]
> This issue is different from #864 right?

Yes, it is different because I will be working for the background of testimonial and #864 for the responsiveness of testimonial.
