### ISSUE TITLE
Button positions not optimized for mobile and tablet view

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#865]
### **Describe the bug**
Button positions not optimized for mobile and tablet view.
In tablet view they are not correctly responsive, some buttons go on next line in tablet view while some don't and sometimes they overlap a little.
![image](https://user-images.githubusercontent.com/54665036/118136817-27875380-b422-11eb-9053-710cf89123c0.png)

![image](https://user-images.githubusercontent.com/54665036/118136776-19d1ce00-b422-11eb-90f8-068b5432244e.png)

![image](https://user-images.githubusercontent.com/54665036/118136876-366e0600-b422-11eb-88cc-7e189e637ea5.png)

For mobile view the buttons are sometimes hard to distinguish, they need some more separation or some other fix.
![image](https://user-images.githubusercontent.com/54665036/118137028-5bfb0f80-b422-11eb-83bb-deb998dff30a.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
@Pranav016 take a look at this.
![image](https://user-images.githubusercontent.com/77333275/118149119-dfbaf900-b42e-11eb-970a-a0c813ec3621.png)

![image](https://user-images.githubusercontent.com/77333275/118149167-efd2d880-b42e-11eb-9ed7-de13e886e375.png)
![image](https://user-images.githubusercontent.com/77333275/118149244-ff522180-b42e-11eb-81ee-a9be403e5bb3.png)

**Comment by tanishq-arya** [comment]
the last one is looking better with 
[one]
[two] 
rather than [one | two] and the button extends beyond if I try to get them in one row
