### ISSUE TITLE
Improve Contact-Us page UI

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#867]
### Bug description-
- the margins on the form are not correctly set and they need to be redone to avoid horizontal scrolling.
- The button is not styled, style it like the rest of the buttons on the website. (orange button) and remove the old css of the button.
- button is also less responsive.

https://user-images.githubusercontent.com/54665036/118138392-e1cb8a80-b423-11eb-8170-1599e56cabe1.mp4

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ankita297** [comment]
Sir the UI  of contact us page is already enhanced .

**Comment by Pranav016** [comment]
> Sir the UI of contact us page is already enhanced .

There are a couple bugs, check issue description

**Comment by Ankita297** [comment]
Sir the  new ui of contact us page is this . the PR #856
![WordNook - Google Chrome 12-05-2021 14_23_22](https://user-images.githubusercontent.com/67833077/118144265-df6c2f00-b429-11eb-898e-6f16d512876f.png)
![WordNook - Google Chrome 12-05-2021 14_23_32](https://user-images.githubusercontent.com/67833077/118144307-e85d0080-b429-11eb-9486-331c629b149b.png)

**Comment by tanishq-arya** [comment]
@Pranav016 Is this okay ? I modified the box-shadow too.
![image](https://user-images.githubusercontent.com/77333275/118152706-a4bac480-b432-11eb-8352-0060a6516a4a.png)

**Comment by tanishq-arya** [comment]
@Pranav016  Should I make a PR for this ?

**Comment by Pranav016** [comment]
I think this issue was already solved..

**Comment by Pranav016** [comment]
Repeated issue #838
