### ISSUE TITLE
Positioning of buttons for smaller screens

### ISSUE THREAD

**Issue by satcasm** [ALPHAVIO/WordNook#873]
Would like to improve upon the positioning of ```ALPHAVIO Bot``` button and ```theme toggle``` button on smaller screens under GSSOC' 21.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/118169485-9ecede80-b446-11eb-854f-a40f8fe006e5.png)

**Comment by tanishq-arya** [comment]
Copy of #863

**Comment by satcasm** [comment]
Closing the issue as it already exists.
