### ISSUE TITLE
Adding proper validation in login and sign up form

### ISSUE THREAD

**Issue by AbhipsaGuru1012** [ALPHAVIO/WordNook#877]
### Feature request-
A clear and concise description of the feature.

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe the solution you'd like
Currently there is a default validation in the form. I would like to add bootstrap validation to it.

### Additional context
![validation](https://user-images.githubusercontent.com/58511560/118231193-62ce6480-b4ac-11eb-8080-aceda1c1c97c.PNG)

I would like to work on this issue under GSSoC'21

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
Can i get some info on this issue ?
Isn't validation already present
