### ISSUE TITLE
Controllers need to be separated from the routes handler || Code refactor for scalability

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#892]
### Feature request-
Right now we are not completely using the MVC model for our development. The controllers are still present in the routers which is not a good practice. We need to separate out all the controllers from the routes and then link them there to ensure scalability of the website thus you need to restructure the code to separate out all the controllers and link them to the routes under this issue.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by GuptaTanisha** [comment]
Please assign this to me.

**Comment by Pranav016** [comment]
> Please assign this to me.

Read the note under the issue

**Comment by Sukriti-sood** [comment]
@Pranav016 Can I go for it?

**Comment by kumarshobhit** [comment]
I would like to work on this. I am lgm-soc participant
