### ISSUE TITLE
SignUp Form UI Modification

### ISSUE THREAD

**Issue by Sristi27** [ALPHAVIO/WordNook#895]
### **Describe the bug**
The Upload Image Label in Signup Form is not clearly visible.Also,we can add an image upload button such that the default file input is hidden.

![Screenshot 2021-05-18 at 1 32 10 AM](https://user-images.githubusercontent.com/53037053/118549410-094e8a00-b779-11eb-932c-600e88ec6ae3.png)

### **Expected behavior**
To add a custom file upload button that will enhance the look of the page and also work according to the functionality

### **Additional context**

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21. Yes
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Ankita297** [comment]
@Pranav016 Can i work on this ?

**Comment by ujju20** [comment]
what to do in this issue the things mentioned in this issue are visible on the website?

**Comment by Pranav016** [comment]
I think the background changes so the text is much more visible now thus closing issue
