### ISSUE TITLE
Backend: admin feature Dicussion

### ISSUE THREAD

**Issue by Subham142** [ALPHAVIO/WordNook#906]
Feature request-
An admin can
->fetch all the users
->edit/delete the user's profile
->fetch every blog
-> delete or update it

Describe the solution you'd like
editing to the userSchema and making routes and controller for it

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21. Yes
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Subham142** [comment]
@Pranav016  what is your thought on this feature

**Comment by Pranav016** [comment]
Sounds good but a bit tricky to implement since you will need to add an 'if else' statements or a new implementation for all the routes. Its upto you if you are willing to work, I'll definitely help you out. I'd suggest raise smaller issues to lead up to this issue so you get more points since this feature could need some large code changes.

**Comment by Subham142** [comment]
> Sounds good but a bit tricky to implement since you will need to add an 'if else' statements or a new implementation for all the routes. Its upto you if you are willing to work, I'll definitely help you out. I'd suggest raise smaller issues to lead up to this issue so you get more points since this feature could need some large code changes.

Yes I would start with a middleware and schema update and after your approval all routes and controllers
