### ISSUE TITLE
UI: Testimonials Wall

### ISSUE THREAD

**Issue by tanishq-arya** [ALPHAVIO/WordNook#910]
### Feature request-
The testimonials wall is not as much clear and appealing.

### Describe the solution you'd like
I would like to change the font styles and make each testimonial appear as a card.

### Additional context
![image](https://user-images.githubusercontent.com/77333275/119170744-52f0ea80-ba81-11eb-9789-e67c4dcd637d.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
@Pranav016 Please assign this issue to me.

**Comment by Ayush0730** [comment]
Check #793 . I think this is similar

**Comment by Pranav016** [comment]
repeated #793

**Comment by tanishq-arya** [comment]
Sorry I didn't see that one.

**Comment by Pranav016** [comment]
> Sorry I didn't see that one.

No problem
