### ISSUE TITLE
Design a new banner for the repo README

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#911]
### Feature request-
New banner needs to be designed for the project. Current banner has our older logo thus the need to change it.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
@Pranav016 Please take a look at this and let me know if yo like it or should I try something else  
![image](https://user-images.githubusercontent.com/77333275/119217324-195ac680-baf7-11eb-8a7b-2535d805f837.png)

![image](https://user-images.githubusercontent.com/77333275/119217330-224b9800-baf7-11eb-8a13-822c8c3649a9.png)

**Comment by Pranav016** [comment]
Something else

**Comment by tanishq-arya** [comment]
Do you have something in mind ?

**Comment by Pranav016** [comment]
> Do you have something in mind ?

Something similar to our current banner..
Current banner is very stylish.

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/119218472-17483600-bafe-11eb-9e3d-c71c0945cfd4.png)

**Comment by tanishq-arya** [comment]
> > Do you have something in mind ?
> 
> Something similar to our current banner..
> Current banner is very stylish.

Okay. I'll try something different then.

**Comment by aanchalrakheja** [comment]
would like to work on this issue.

**Comment by tanishq-arya** [comment]
@Pranav016 What about this ?
![image](https://user-images.githubusercontent.com/77333275/119230305-3dd79280-bb39-11eb-8fbc-298215c74cb8.png)

**Comment by aanchalrakheja** [comment]
![1](https://user-images.githubusercontent.com/68388581/119242342-a72bc580-bb7a-11eb-82f3-9630ba51e94e.png)
![2](https://user-images.githubusercontent.com/68388581/119242343-a85cf280-bb7a-11eb-8f68-0e948321f4bf.png)
![3](https://user-images.githubusercontent.com/68388581/119242345-a8f58900-bb7a-11eb-9806-35eb91d465d2.png)
Something like this? will try some more

**Comment by Pranav016** [comment]
> ![1](https://user-images.githubusercontent.com/68388581/119242342-a72bc580-bb7a-11eb-82f3-9630ba51e94e.png)
> ![2](https://user-images.githubusercontent.com/68388581/119242343-a85cf280-bb7a-11eb-8f68-0e948321f4bf.png)
> ![3](https://user-images.githubusercontent.com/68388581/119242345-a8f58900-bb7a-11eb-9806-35eb91d465d2.png)
> Something like this? will try some more

Nope

**Comment by Pranav016** [comment]
> @Pranav016 What about this ?
> ![image](https://user-images.githubusercontent.com/77333275/119230305-3dd79280-bb39-11eb-8fbc-298215c74cb8.png)

Better but the components are not blended, I can still see all the boundaries of the pictures that don't match the background..

**Comment by tanishq-arya** [comment]
> > @Pranav016 What about this ?
> > ![image](https://user-images.githubusercontent.com/77333275/119230305-3dd79280-bb39-11eb-8fbc-298215c74cb8.png)
> 
> Better but the components are not blended, I can still see all the boundaries of the pictures that don't match the background..

The gray background is not a part of the banner. You are talking about the mongoose one right ?

**Comment by aanchalrakheja** [comment]
![banner1](https://user-images.githubusercontent.com/68388581/119257923-20600280-bbe5-11eb-8959-b567c8038cd3.png)
This?

**Comment by aanchalrakheja** [comment]
![5](https://user-images.githubusercontent.com/68388581/119259998-72f1ec80-bbee-11eb-9427-0061709816df.png)
![6](https://user-images.githubusercontent.com/68388581/119260003-784f3700-bbee-11eb-80a1-afb0090fd34b.png)
![8](https://user-images.githubusercontent.com/68388581/119260005-78e7cd80-bbee-11eb-86e3-0d3f6a316928.png)

**Comment by Pranav016** [comment]
![image](https://user-images.githubusercontent.com/54665036/119264052-3c709d80-bbff-11eb-8fbe-3d3f53b63184.png)

@aanchalrakheja  This one looks really nice, let's go with this one..

**Comment by aanchalrakheja** [comment]
Ok. Will continue with it.

**Comment by aanchalrakheja** [comment]
Can you please guide me a bit about how to go about updating it.
