### ISSUE TITLE
Update demo gif in README

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#912]
### Feature request-
Update demo gif in README with the new changes.

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by aanchalrakheja** [comment]
Hey! I had a doubt. When I am signing up its showing an error. How do I continue making a gif.

**Comment by Pranav016** [comment]
> Hey! I had a doubt. When I am signing up its showing an error. How do I continue making a gif.

Yes, check #780. I would suggest make the gif while running the website on your local server, then I think you would be able to sign in..

**Comment by aanchalrakheja** [comment]
Ok will try

**Comment by aanchalrakheja** [comment]
I tried recording the screen but the website is getting hanged alot which is creating a very long video including all steps and even the size is becoming very big. Can u suggest some alternative.

**Comment by Pranav016** [comment]
> I tried recording the screen but the website is getting hanged alot which is creating a very long video including all steps and even the size is becoming very big. Can u suggest some alternative.

Video does get long sometimes don't worry, create the gif.

What is the size of the video?

**Comment by aanchalrakheja** [comment]
It was exceeding around 20MB. I am trying once again. Will fix it by tomorrow.
