### ISSUE TITLE
Create Full screen Overlay Navigation Bar for mobile and tablet view

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#914]
### Feature request-
Create Full screen Overlay Navigation Bar for mobile and tablet view.

( Google it if you don't know about Full Screen Overlay Navigation Bar. )

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by tanishq-arya** [comment]
@Pranav016 How is this ?
https://user-images.githubusercontent.com/77333275/119512257-c56b0e80-bd90-11eb-9faa-0019fc38d933.mp4

**Comment by Pranav016** [comment]
> @Pranav016 How is this ?
> https://user-images.githubusercontent.com/77333275/119512257-c56b0e80-bd90-11eb-9faa-0019fc38d933.mp4

Can we have the animation to be to the right or left instead of downwards since earlier we were having downwards animation on the navbar toggle. Let me know if this is unclear..

**Comment by tanishq-arya** [comment]
Okay I'll try that.
