### ISSUE TITLE
Inconsistency in form styling [Edit Blog Form]

### ISSUE THREAD

**Issue by Ayush0730** [ALPHAVIO/WordNook#950]
### Feature request-
I think all forms should look similar in appearance. This issue needs some suggestions

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context
Login/Signup/Edit Blog forms looks like this 
![image](https://user-images.githubusercontent.com/68139755/120017238-44677d80-c003-11eb-8761-94f4e2b74a4f.png)

Compose/ Edit Profile Forms looks like 
![image](https://user-images.githubusercontent.com/68139755/120017388-7547b280-c003-11eb-9118-2643d20dda2c.png)

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
> @Pranav016 I need some suggestions for this, What should I do:
> 
> 1. Change all forms to look like Compose Form
> 2. Keep login/signup form same and just modify Edit Blog form
> 3. Or any other Suggestion?

Do option 2 for this issue. And then login and sign up form in separate PR.

**Comment by Ayush0730** [comment]
> > @Pranav016 I need some suggestions for this, What should I do:
> > 
> > 1. Change all forms to look like Compose Form
> > 2. Keep login/signup form same and just modify Edit Blog form
> > 3. Or any other Suggestion?
> 
> Do option 2 for this issue. And then work on login and sign up form in separate PR.
> 
> Don't do all forms in one PR.

Okay
