### ISSUE TITLE
Github Bot Feature

### ISSUE THREAD

**Issue by Sukriti-sood** [ALPHAVIO/WordNook#963]
### Feature request-
Github Bot Will COmment on Every PR Open and PR merged

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

Working Under GSSOC

**Comment by Pranav016** [comment]
We have a bot that comments on every PR and issue created by a new contributor. I don't think there is anything that we need to comment on every PR or issue..

Closing this issue for now since I don't think it is required, but you can comment if you feel the usecase is different.

**Comment by Sukriti-sood** [comment]
@Pranav016  Current Github Bot did not comment on the merging of the PR (not for first contributor),.

**Comment by Pranav016** [comment]
> @Pranav016 Current Github Bot did not comment on the merging of the PR (not for first contributor),.

What should it be commenting on merging the PR?

**Comment by Sukriti-sood** [comment]
> > @Pranav016 Current Github Bot did not comment on the merging of the PR (not for first contributor),.
> 
> What should it be commenting on merging the PR?

@user Hurray your First PR Got Merged (some emoji) , Feel free to take another Issue ,

Any customize message can be added if you want.

**Comment by Pranav016** [comment]
> > > @Pranav016 Current Github Bot did not comment on the merging of the PR (not for first contributor),.
> > 
> > 
> > What should it be commenting on merging the PR?
> 
> @user Hurray your First PR Got Merged (some emoji) , Feel free to take another Issue ,
> 
> Any customize message can be added if you want.

I would maybe like this if I am contributing to the project for the first time. If it as an experienced person, I don't think they would care.

**Comment by Sukriti-sood** [comment]
> > > > @Pranav016 Current Github Bot did not comment on the merging of the PR (not for first contributor),.
> > > 
> > > 
> > > What should it be commenting on merging the PR?
> > 
> > 
> > @user Hurray your First PR Got Merged (some emoji) , Feel free to take another Issue ,
> > Any customize message can be added if you want.
> 
> Maybe I would like this if I am contributing to the project for the first time. If it as an experienced person, I don't think they would care.

Yeah that's true, I only suggested you for first time contributors,

**Comment by Pranav016** [comment]
> > > > > @Pranav016 Current Github Bot did not comment on the merging of the PR (not for first contributor),.
> > > > 
> > > > 
> > > > What should it be commenting on merging the PR?
> > > 
> > > 
> > > @user Hurray your First PR Got Merged (some emoji) , Feel free to take another Issue ,
> > > Any customize message can be added if you want.
> > 
> > 
> > Maybe I would like this if I am contributing to the project for the first time. If it as an experienced person, I don't think they would care.
> 
> Yeah that's true, I only suggested you for first time contributors,

Ok, you can do it for first time contributors.

**Comment by ujju20** [comment]
So I have to make a separate bot or modify the GitHub actions included in the project?

**Comment by Pranav016** [comment]
> So I have to make a separate bot or modify the GitHub actions included in the project?

It's upto you how you want to do it as long as it works👍

**Comment by ujju20** [comment]
> > So I have to make a separate bot or modify the GitHub actions included in the project?
> 
> It's upto you how you want to do it as long as it works

Ok 👍🏻
