### ISSUE TITLE
Improve testimonial wall UI for mobile view

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#982]
### Feature request-
The testimonials in testimonial wall are very thin in mobile view thus the text doesn't look good. Make the testimonial cards a little wider and reduce the padding given to the text inside the card so that it can take up more space.
![image](https://user-images.githubusercontent.com/54665036/120530946-b07b2480-c3fb-11eb-8a2f-eee69a23e05e.png)

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Ayush0730** [comment]
@RakeshCharpe Are you still working on this issue?

**Comment by RakeshCharpe** [comment]
Yes

**Comment by Ayush0730** [comment]
> Yes

Can you please fix this issue in 1 or 2 days?

**Comment by RakeshCharpe** [comment]
@Ayush0730  I tried because of my colleges exam it delay.
