### ISSUE TITLE
Overlapping buttons in carousel

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#983]
### **Describe the bug**
The buttons in the testimonial carousel are overlapping in mobile view.
![image](https://user-images.githubusercontent.com/54665036/120531268-14055200-c3fc-11eb-97cc-1af41d93f9f9.png)

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by RR-Sahoo** [comment]
hyy can I work on this issue.

**Comment by SamikshaSankar** [comment]
I can work on this issue under LGM-SOC'21 participant..please assigned me

**Comment by Ayush0730** [comment]
@SamikshaSankar Any updates? Are you still working on the issue?
