### ISSUE TITLE
Sign-up form is not responsive for mobile view

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#984]
### **Describe the bug**
Sign-up form is not responsive for mobile view.

https://user-images.githubusercontent.com/54665036/120531747-9a219880-c3fc-11eb-9ee3-beb828a1e6ec.mp4

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by ss-sahoo** [comment]
Hyy  can I work on this issue

**Comment by RR-Sahoo** [comment]
hyy can I work on this issue.

**Comment by Ayush0730** [comment]
> hyy can I work on this issue.

You can comment ```/assign``` to get the issue assigned to you if no one is assigned (issue is free).

**Comment by Ayush0730** [comment]
@aanchalrakheja Are you working on this?

**Comment by aanchalrakheja** [comment]
> @aanchalrakheja Are you working on this?

Yes i m working on it.

**Comment by aanchalrakheja** [comment]
![image](https://user-images.githubusercontent.com/68388581/123969620-054b9400-d9d6-11eb-872c-872a9b497541.png)
Can you help me out with styling the Recaptcha box. How do i target it?

**Comment by Ayush0730** [comment]
I think you have to target this 
![image](https://user-images.githubusercontent.com/68139755/124160737-33a29f80-daba-11eb-96a5-7c26f4f83be9.png)

Or this
![image](https://user-images.githubusercontent.com/68139755/124160785-41f0bb80-daba-11eb-8169-07ad13f71233.png)

**Comment by Pranav016** [comment]
> ![image](https://user-images.githubusercontent.com/68388581/123969620-054b9400-d9d6-11eb-872c-872a9b497541.png)
> Can you help me out with styling the Recaptcha box. How do i target it?

Use the small arrow/ cursor button on top left of the dev tools, when you hover it over any element it will show its code/ place in dom.
