### ISSUE TITLE
Inconsistency in button color

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#987]
### **Describe the bug**
The buttons on home page show different colors on hover/ click whereas they should all have the same color

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Pranav016** [comment]
> /assign

Are you working under some program?

**Comment by RakeshCharpe** [comment]
Yes ,GSsoc'21

**Comment by Pranav016** [comment]
> Yes ,GSsoc'21

GSSoC is over, they have told us to not to accept any more PRs under GSSoC.

**Comment by RakeshCharpe** [comment]
Ok, I see this project in under letsgrow projects to contribute ,now i am selected in it for contribution So can i contribute in it ?

**Comment by Pranav016** [comment]
> Ok, I see this project in under letsgrow projects to contribute ,I am selected in it for contribution So can i contribute in it ?

Sure, you can contribute to it but we have been adviced to assign issues during coding period.

**Comment by RakeshCharpe** [comment]
Ok sure sir, I will contribute in coding period .

**Comment by RakeshCharpe** [comment]
On click or hover what you want color should be changed or not.

**Comment by Pranav016** [comment]
I will add more info to this issue tomorrow, will add some screenshots to explain better👍
