### ISSUE TITLE
Newsletter sign-up is unresponsive and unstyled

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#988]
### **Describe the bug**
Newsletter sign-up is unresponsive and unstyled. Make the button look the other buttons on the website, style the card and make it responsive.

https://user-images.githubusercontent.com/54665036/120535293-72343400-c400-11eb-95df-8e12d1866f52.mp4

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by jugeshraghav** [comment]
Hello! Can I work on the issue as I am a participant of LM-SoC

**Comment by Ayush0730** [comment]
@yashraj-02-techie Are you working on this?
