### ISSUE TITLE
Update profile form is unresponsive for mobile view

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#989]
### **Describe the bug**
Update profile form in dashboard is unresponsive for mobile view
![image](https://user-images.githubusercontent.com/54665036/120535583-cd662680-c400-11eb-91f8-acf841ad93f3.png)

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Ayush0730** [comment]
@Aiswarika Are you still working on this issue?

**Comment by heet-kumar** [comment]
I am also working under the LGMSOC'21 for just informing you.

**Comment by MukulKolpe** [comment]
@Ayush0730 can I work in this issue ?

**Comment by theBeginner86** [comment]
@heet-kumar are you still working on this issue?

**Comment by theBeginner86** [comment]
@MukulKolpe just wait for some time, if we don't get a response from @heet-kumar then we would assign you this issue. 😊

**Comment by MukulKolpe** [comment]
sure

**Comment by heet-kumar** [comment]
@theBeginner86 I am working on it bro so wait it nearly to complete

**Comment by Ayush0730** [comment]
> @theBeginner86 I am working on it bro so wait it nearly to complete

Sure, but can you please create PR ASAP

**Comment by theBeginner86** [comment]
and 
@MukulKolpe I would suggest you to take up other open issues as @heet-kumar is still working on it. 👍👨‍💻
