### ISSUE TITLE
Bug in profile image sizing

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#990]
### **Describe the bug**
The size of profile image currently changes with the image that is added. This shouldn't happen, profile image should stay circular and of same size.
![image](https://user-images.githubusercontent.com/54665036/120536554-e1f6ee80-c401-11eb-9218-bdf61a39bc16.png)

![image](https://user-images.githubusercontent.com/54665036/120537405-e1128c80-c402-11eb-8265-895ee9fe0907.png)

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Ayush0730** [comment]
@SamikshaSankar Are you still working on this issue?

**Comment by SamikshaSankar** [comment]
Yes

**Comment by Pranav016** [comment]
> Yes

Please make your PR asap.

**Comment by SamikshaSankar** [comment]
@Pranav016 there is no bug in profile picture 

![2021-06-21](https://user-images.githubusercontent.com/52104082/122729647-00306b80-d297-11eb-9376-34cd46cbc022.png)

**Comment by Pranav016** [comment]
> @Pranav016 there is no bug in profile picture
> 
> ![2021-06-21](https://user-images.githubusercontent.com/52104082/122729647-00306b80-d297-11eb-9376-34cd46cbc022.png)

It changes with profile picture sizes, try a couple times with profile picture of variable sizes.
