### ISSUE TITLE
Search feature not working

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#993]
### **Describe the bug**
Search feature on the home page is not working

### **To Reproduce**
1. Search a random string

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by akshikamudgal** [comment]
Can I work on it.
/assign

**Comment by jayant766** [comment]
Adding an If condition to check for the internet

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by Pranav016** [comment]
> I couldn't get the code on which I need to work.
> guide me the html file in which the error is to be fixed.

The frontend for search is here- views/navitems/home.ejs
I checked the routes for the backend and I can't seem to find it either. I think some commit must removed it by mistake. You can add it again under this issue. Take reference from #31

**Comment by Amishakumari544** [comment]
Hey, any updates on this??
If not i want to work under lgm soc21

**Comment by Pranav016** [comment]
@akshikamudgal are you still working on this?

**Comment by akshikamudgal** [comment]
> @akshikamudgal are you still working on this?

No

**Comment by RituCs** [comment]
I would like to work on this issue if no one is working on this.
